### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by hobbyquaker** [mdzio/ccu-jack#1]
Cooles Projekt, gefällt mir. Aber warum ist der Source nicht im Repo? :-)

**Comment by mdzio** [comment]
Eine Veröffentlichung der Quelltexte ist geplant. Allerdings will ich sie vorher nochmal überarbeiten und den Build-Prozess vereinfachen, damit andere Entwickler einen leichten Einstieg haben.

Es wird also ähnlich wie beim CCU-Historian ablaufen.

**Comment by psi-4ward** [comment]
Ich wäre auch an den Sourcen interessiert! Done is better than perfect :)

**Comment by mdzio** [comment]
Es gab nun schon einige Anfragen. Ich werde die Veröffentlichung als Nächstes angehen, sobald das aktuelle Feature fertig ist. Das Issue öffne ich wieder, damit es weniger Verwirrung gibt.

**Comment by mdzio** [comment]
Die Quellen sind nun verfügbar. Fragen werden gerne beantwortet.
