### ISSUE TITLE
Löschen von Geräten aus CCU

### ISSUE THREAD

**Issue by ptweety** [mdzio/ccu-jack#101]
Hi,

wenn man Geräte aus der CCU löscht, dann bemerkt dies CCU-Jack korrekt und zeigt diese auch nicht mehr über den veap-Dienst oder den Navigator an.

Allerdings sind die nunmehr ungültigen mqtt-Topics weiterhin vorhanden.

**Comment by mdzio** [comment]
Der CCU-Jack publiziert MQTT-Nachrichten für alle Datenpunkte außer ACTION mit dem Retained-Flag, wodurch der MQTT-Server immer die letzte Nachricht im Arbeitsspeicher vorhält. Neu verbundene MQTT-Clients bekommen den letzten Wert dadurch sofort zur Verfügung gestellt und müssen nicht bis zur nächsten Wertaktualisierung warten.

Eine automatische Löschung ist zu aufwändig für den Nutzen. Nach einem Neustart sind sie auch nicht mehr vorhanden.
