### ISSUE TITLE
MQTT: Publizierung von sysVar Values

### ISSUE THREAD

**Issue by djiwondee** [mdzio/ccu-jack#102]
Hallo @mdzio 

vielen Dank für dieses tolle CCU-Addon!!! 

Ich habe eine Frage zu den verfügbaren über MQTT publizierten Messages. Aktuell werden _nur_ für Geräte Nachrichten publiziert?

Anders als es diese Info zu den MQTT-Topics mutmaßen lässt, werden Wert(änderungen) für Variablen nicht auf dem MQTT-Broker geschrieben?

<img width="561" alt="image" src="https://user-images.githubusercontent.com/37173958/195329614-00e1dd80-6e1a-4985-8b82-d59e030112a8.png">

Vielen Dank für eine Rückantwort!

**Comment by mdzio** [comment]
In der Beschreibung der Systemvariable muss das Schlüsselwort **MQTT** irgendwo auftauchen, dann liest der CCU-Jack zyklisch den Wert und publiziert ihn über MQTT. [Siehe auch im Handbuch Abschnitt MQTT Server.](https://github.com/mdzio/ccu-jack/wiki/MQTT-Server)
