### ISSUE TITLE
Direkt Verknüpfungen

### ISSUE THREAD

**Issue by jonaswre** [mdzio/ccu-jack#103]
Hallo, ich habe in der Dokumentation/Issues leider keine Referenz zum anlegen/konfigurieren von Direkt Verknüpfungen gefunden. Ist das möglich?

**Comment by jonaswre** [comment]
Wenn das hier nicht der richtige Ort für solche Fragen ist. Gibt es dann ein Forum?

**Comment by mdzio** [comment]
Der CCU-Jack unterstützt keine Direktverknüpfungen seiner virtuellen Geräte untereinander. Das ist auch zu aufwändig umzusetzen.

Direktverknüpfungen können sowieso nur innerhalb einer Gerätefamilie (z.B. BidCos-Rf mit BidCos-Rf oder HmIP mit HmIP) erstellt werden.

**Comment by jonaswre** [comment]
Vielen dank für die Antwort.

Ich meinte auch Direkt Verbindungen zwischen echten Geräten. 
Direkt Verbindungen in der JSON API sind Paramsets wo der Paramkey die Sender Adresse ist. 
Deswegen hatte ich gehofft das die REST API diese Datenpunkte unterstützt.

**Comment by mdzio** [comment]
Du meinst also das Lesen und Schreiben des LINK-Paramsets der Geräte. Das geht aber schon zu sehr in Richtung Konfiguration/Projektierung, was über das ursprüngliche Ziel des CCU-Jacks hinaus schießt. 

Der CCU-Jack unterstützt zwar den MASTER-Paramset. Dort gibt es aber den Anwendungsfall, dass Werte häufig im laufenden Betrieb angepasst werden müssen.

**Comment by jonaswre** [comment]
Ja genau ich wollte CCU-Jack für Konfiguration benutzen. Aber vielleicht bin ich dann doch mit XML-RPC besser beraten. Ich hatte nur gehofft es gäbe eventuell eine besser Möglichkeit.
