### ISSUE TITLE
CCU-Jack-UI unter Homeassistant mit Raspberrymatic nicht aufrufbar (Port 2121)

### ISSUE THREAD

**Issue by guenter-ms** [mdzio/ccu-jack#104]
Hallo,

ich habe auf dem pi3b das Raspberrymatic addon unter Homeassistant erfolgreich installiert.

Dann habe ich das CCU-addon "CCU-Jack" über die CCU-Zentrale/Systemeinstellungen/Zusatzsoftware ebenfalls erfolgreich installiert.

Wenn ich dann den neuen Button "CCU-Jack" betätige, erhalte ich im Browser eine 404-Fehlermeldung, not found.

Was kann ich tun?

Details siehe unten.

![Bildschirmfoto 2022-10-24 um 12 06 36](https://user-images.githubusercontent.com/6253315/197502419-67d6b282-4598-4d28-89f2-38cc6734f7ab.jpg)

![Bildschirmfoto 2022-10-24 um 12 07 17](https://user-images.githubusercontent.com/6253315/197502542-008416a0-7332-4c73-a336-9d7ecd573494.jpg)

![Bildschirmfoto 2022-10-24 um 12 07 51](https://user-images.githubusercontent.com/6253315/197502636-c8bbc76b-c739-46a1-ab24-160caed59aba.jpg)

**Comment by guenter-ms** [comment]
Habe gerade mal das respository von https://github.com/jens-maus/RaspberryMatic runtergeladen und entzippt.

Im folder home-assistant-addon finde ich die Datei config.yaml.


![Bildschirmfoto 2022-10-24 um 12 59 12](https://user-images.githubusercontent.com/6253315/197511258-a7ff6677-e33f-4f59-bd30-379ecf58f913.jpg)


Diese Datei enthält Konfigurationsinfos für die ports.

Die CCU-Jack ports sind da nicht enthalten (2121,...)

[config.yaml.pdf](https://github.com/mdzio/ccu-jack/files/9851132/config.yaml.pdf)


Demzufolge kann ich in der HA-Raspberrymatic-Konfiguration diese ports auch nicht freigeben:

![Bildschirmfoto 2022-10-24 um 13 05 43](https://user-images.githubusercontent.com/6253315/197512195-5f0ba789-b35b-4230-b0ac-bb9cf5937de6.jpg)


Was meinst du?

**Comment by ptweety** [comment]
Ich denke, da kann dir hier nicht so gut geholfen werden. Wende dich doch besser mal ans entsprechend andere Projekt.

**Comment by mdzio** [comment]
Ich schließe den Eintrag hier, da das Problem in RaspberryMatic gelöst werden muss.

**Comment by guenter-ms** [comment]
Vielen Dank!
