### ISSUE TITLE
Virtuelle Geräte: MQTT-Schaltktor mit Leistungsmessung / Stromzähler

### ISSUE THREAD

**Issue by Baxxy13** [mdzio/ccu-jack#105]
Uwe hat's mit CUxD vorgemacht, es gibt jetzt einen HM-ES-PMSw1 bei dem alle Datenpunkte (Energie-Zähler, Spannung, Strom, Leistung, Netzfrequenz) beschrieben werden können.

Das würde mir als virtuelles Jack-Device auch gefallen (zur Anbindung eines Modbus-Stromzählers oder einer Tasmota Schaltsteckdose).

Vorlagen:
HM-ES-PMSw1 / HmIP-PSM

Alternativ als reinen Stromzähler:
(Energiezähler / Leistung)
HM-ES-TX-WM

**Comment by mdzio** [comment]
Ich besitze selber die drei genannten Geräte nicht. Wie sehen sie denn unter _Status und Bedienung_ → _Geräte_ auf der CCU aus?
Und welche Kanäle besitzen sie (unter _Einstellungen_ → _Geräte_)?

**Comment by Baxxy13** [comment]
Ich habe jetzt mal alle 3 von mir erwähnten Geräte verglichen und würde dem HM-ES-PMSw1 als "Universalgerät" den Vorzug geben. Die HmIP-PSM hat ja die virtuellen Kanäle die wir hier nicht brauchen und der HM-ES-TX-WM hat 2 verschiedene Firmwares mit entsprechend anderer Darstellung in der WebUI.

Also der HM-ES-PMSw1:
Status und Bedienung → Geräte:
![PMSw1_SuB_G](https://user-images.githubusercontent.com/54898249/204161642-e3a4a371-1c88-48c0-bbd0-1d6c8c877707.JPG)
In dieser Ansicht unterscheidet sich der echte Aktor nicht vom CUxD-Gerät

Einstellungen → Geräte:
![PMSw1_Einst_G](https://user-images.githubusercontent.com/54898249/204161695-7f408d09-3c38-4e2f-b802-c1832356ee9e.JPG)
Die obere Klammer zeigt das CUxD-Gerät, die untere den echten Aktor. Für den Jack würden die Kanäle des CUxD-Gerätes reichen, :3 - :6 des echten Aktor sind zum einstellen der Entscheidungswerte die dann in DV's zum tragen kommen.

Wenn du den aktuellen CUxD auf einer deiner Zentralen/Testsysteme laufen hast kannst du den Aktor auch selbst anlegen Typ (28) System / Funktion: ES-PMSw1

**Comment by mdzio** [comment]
Es gibt jetzt (noch nicht veröffentlicht) im CCU-Jack einen virtuellen HM-ES-PMSw1 ohne eigene Logik. Die Datenpunkte können von extern über die REST-API oder über vorgegebene MQTT-Topics gelesen und beschrieben werden.

Wird denn eine MQTT-Anbindung für beliebige Topics benötigt? Zum Beispiel für Tasmota?

**Comment by Baxxy13** [comment]
Hallo Mathias,
das hört sich ja schon mal sehr gut an.

Primär würde ich tatsächlich Tasmota-Schaltsteckdosen anbinden wollen.

Ein MQTT-Modbus-Gateway (verbunden mit einem Modbus Stromzähler) würde ich auch gerne anbinden. 
Da hattest du mir im Forum schon mal [mit dem Regex geholfen](https://homematic-forum.de/forum/viewtopic.php?f=41&t=75288&p=730094&hilit=regex#p730072). Bei dem Teil kann ich aber die Topics nicht anpassen.

Aus meiner Sicht wären also beliebige Topics (inklusive Regex Funktion) am besten. 

Danke für deine Mühe!

**Comment by mdzio** [comment]
Wie sieht denn die MQTT-Nachricht für die Energiewerte bei Tasmota-Schaltsteckdosen aus?

**Comment by Baxxy13** [comment]
Hab jetzt mal eine Tasmota-Dose frisch aus dem Karton mit dem Jack verbunden.
Die 3 Energiezähler:
`Yesterday`
`Total`
`Today`

Sind mit im "SENSOR-Topic" enthalten:
`SENSOR = {"Time":"2022-12-15T17:15:33","ENERGY":{"TotalStartTime":"2022-12-15T15:57:20","Total":0.120,"Yesterday":0.000,"Today":0.120,"Period":9,"Power":510,"ApparentPower":510,"ReactivePower":0,"Factor":1.00,"Voltage":223,"Current":2.284}}`

**Comment by mdzio** [comment]
Der Schaltktor mit Leistungsmessung / Stromzähler **ohne** MQTT wurde implementiert (s. #112).

**Comment by mdzio** [comment]
> Die Einheit der Zähler ist kWh, der HM-ES-PMSw1 zählt aber Wh.

Der Strom hat beim HM-ES-PMSw1 ebenfalls eine andere Einheit: mA. Die Werte können aber mit der TEMPLATE-Methode (siehe auch MQTT Analogeingang) umgerechnet werden.

Die MQTT-Anbindung ist dann in der v2.7.0, die sich gerade bei mir in der Testphase befindet, enthalten.

**Comment by Baxxy13** [comment]
Das hört sich ja super an.
Ich ahne aber schon das ich für die Umrechnungs-Templates Hilfe benötige. :wink:

**Comment by mdzio** [comment]
Die Umrechnung von Werten wird noch nicht unterstützt. Sie wird aber auch noch implementiert (s.a. #117).

**Comment by decanyon** [comment]
Ich kann das Leistungsmesser in den "Virtual Devices" der Version 2.7.0 nicht auswählen. Nur die Static Devices und MQTT Devices, alle ohne die Funktion Leistungsmessung.

**Comment by decanyon** [comment]
> Bitte Mal den Web-Browser-Cache leeren. Mit der Taste F5 sollte auch die Web-UI neu geladen werden.

Danke für die schnelle Rückmeldung. 
Habe gerade mit einem anderen Endgerät festgestellt, dass die virtuellen Kanäle korrekt aufgelistet werden. 
Am Notebook hatte ich vorher das Problem, dass ich in der Liste „neuen Kanal hinzufügen“ den Kanal Temperatursensor sowie Energiemessung (statisch und MQTT) nicht angezeigt bekommen habe. Die Möglichkeit das Gerätesymbol auszuwählen wurde ebenfalls nicht angezeigt. 

Werde den Cache leeren und das nochmal auf Reproduzierbarkeit prüfen. Die Umgebung auf dem „Problemsystem“ besteht aus Win10 und dem Edge Browser.
