### ISSUE TITLE
CONTROL_MODE liefert stets {"ts":0,"v":0,"s":100}

### ISSUE THREAD

**Issue by biglouis** [mdzio/ccu-jack#106]
Setzen des Parameters CONTROL_MODE mittels PUT funktioniert, lesen mit GET liefert unabhängig vom tatsächlichen Wert immer {"ts":0,"v":0,"s":100}. Sowohl auf einem HmIP-WTH-B als auch auf einem HmIP-STH. Andere Datenpunkte wie z.B. ACTIVE_PROFILE funktionieren ohne Probleme.

CCU JACK: V2.5.0
CCU3: 3.65.11
HmIP-STH: 2.8.2
HmIP-WTH-B: 1.0.12

Beispiel-URL: http://--IP_ENTFERNT__:2121/device/--ID_ENTFERNT--/1/CONTROL_MODE/~pv

**Comment by mdzio** [comment]
Die Geräte besitze ich selber nicht. Was wird denn bei den Eigenschaften _flags_ und _operations_ im Navigator des CCU-Jacks zu diesem Datenpunkt angezeigt?

**Comment by biglouis** [comment]
Danke, das lieferte den letztendlichen Hinweis. In

`
{"address":"000E5F298E3FE3:1","aesActive":1,"availableFirmware":"","children":null,"direction":1,"firmware":"","flags":1,"group":"","identifier":"1","index":1,"interface":"","linkSourceRoles":"CLIMATE_CONTROL_WTH_TRV","linkTargetRoles":"","paramsets":["MASTER","VALUES","LINK","SERVICE"],"parent":"000E5F298E3FE3","parentType":"HmIP-STH","rfAddress":0,"roaming":0,"rxMode":0,"team":"","teamChannels":null,"teamTag":"","title":"Thermostat.Dusche.Datenpunkte","type":"HEATING_CLIMATECONTROL_TRANSCEIVER","version":5,"~links":[{"rel":"parameter","href":"ACTIVE_PROFILE","title":"Thermostat.Dusche.Datenpunkte - ACTIVE_PROFILE"},{"rel":"parameter","href":"BOOST_TIME","title":"Thermostat.Dusche.Datenpunkte - BOOST_TIME"},{"rel":"parameter","href":"DURATION_VALUE","title":"Thermostat.Dusche.Datenpunkte - DURATION_VALUE"},{"rel":"parameter","href":"CONTROL_DIFFERENTIAL_TEMPERATURE","title":"Thermostat.Dusche.Datenpunkte - CONTROL_DIFFERENTIAL_TEMPERATURE"},{"rel":"parameter","href":"SET_POINT_TEMPERATURE","title":"Thermostat.Dusche.Datenpunkte - SET_POINT_TEMPERATURE"},{"rel":"parameter","href":"PARTY_MODE","title":"Thermostat.Dusche.Datenpunkte - PARTY_MODE"},{"rel":"parameter","href":"BOOST_MODE","title":"Thermostat.Dusche.Datenpunkte - BOOST_MODE"},{"rel":"parameter","href":"PARTY_TIME_END","title":"Thermostat.Dusche.Datenpunkte - PARTY_TIME_END"},{"rel":"parameter","href":"SET_POINT_MODE","title":"Thermostat.Dusche.Datenpunkte - SET_POINT_MODE"},{"rel":"parameter","href":"HUMIDITY","title":"Thermostat.Dusche.Datenpunkte - HUMIDITY"},{"rel":"parameter","href":"QUICK_VETO_TIME","title":"Thermostat.Dusche.Datenpunkte - QUICK_VETO_TIME"},{"rel":"parameter","href":"HEATING_COOLING","title":"Thermostat.Dusche.Datenpunkte - HEATING_COOLING"},{"rel":"parameter","href":"FROST_PROTECTION","title":"Thermostat.Dusche.Datenpunkte - FROST_PROTECTION"},{"rel":"parameter","href":"PARTY_SET_POINT_TEMPERATURE","title":"Thermostat.Dusche.Datenpunkte - PARTY_SET_POINT_TEMPERATURE"},{"rel":"parameter","href":"PARTY_TIME_START","title":"Thermostat.Dusche.Datenpunkte - PARTY_TIME_START"},{"rel":"parameter","href":"WINDOW_STATE","title":"Thermostat.Dusche.Datenpunkte - WINDOW_STATE"},{"rel":"parameter","href":"SWITCH_POINT_OCCURED","title":"Thermostat.Dusche.Datenpunkte - SWITCH_POINT_OCCURED"},{"rel":"parameter","href":"ACTUAL_TEMPERATURE_STATUS","title":"Thermostat.Dusche.Datenpunkte - ACTUAL_TEMPERATURE_STATUS"},{"rel":"parameter","href":"$MASTER","title":"Thermostat.Dusche.Datenpunkte - $MASTER"},{"rel":"parameter","href":"DURATION_UNIT","title":"Thermostat.Dusche.Datenpunkte - DURATION_UNIT"},{"rel":"parameter","href":"CONTROL_MODE","title":"Thermostat.Dusche.Datenpunkte - CONTROL_MODE"},{"rel":"parameter","href":"HUMIDITY_STATUS","title":"Thermostat.Dusche.Datenpunkte - HUMIDITY_STATUS"},{"rel":"parameter","href":"ACTUAL_TEMPERATURE","title":"Thermostat.Dusche.Datenpunkte - ACTUAL_TEMPERATURE"},{"rel":"device","href":"..","title":"Thermostat.Dusche"},{"rel":"room","href":"/room/44634","title":"Dusche"},{"rel":"function","href":"/function/1217","title":"Thermostate"}]}
`

hab ich den SET_POINT_MODE entdeckt, und wenn man dann danach sucht stößt man auf

https://homematic-forum.de/forum/viewtopic.php?t=40993

Dort steht die Lösung. Also

- Empfangen mittels SET_POINT_MODE
- Setzen mittels CONTROL_MODE

Scheint ein Homematic Problem zu sein. Egal, jetzt läuft es.
