### ISSUE TITLE
Startparameter beim Start aus Textdatei lesen

### ISSUE THREAD

**Issue by StefanGubler** [mdzio/ccu-jack#11]
Enhancement Request:
Es wäre von Vorteil, wenn die Startparameter nicht in die Kommandozeile eingegeben werden müsste sondern aus einer Datei gelesen werden könnte, welche im gleichen Verzeichnis liegt wie die ccu-jack exe Datei.
Dies würde eine Plattformübergreifende gleiche Konfiguration ermöglichen
und man müsste bei linux oder ccu dann nicht in die shell scripts für die Startkonfiguration eingreifen, oder bei Windows als Service wären keine Registry oder Batch Datei Änderungen notwendig.

**Comment by mdzio** [comment]
Die Kommandozeilenparameter sollen nun nach und nach in eine Konfigurationsdatei im JSON-Format verschoben werden. Zusätzlich soll die meisten Konfigurationsoptionen auch über die Web-UI geändert werden können.
