### ISSUE TITLE
MQTT Bridge macht weiterhin Verbindungsversuche obwohl in Konfig nicht mehr aktiviert

### ISSUE THREAD

**Issue by addy38** [mdzio/ccu-jack#110]
Hallo, 
ich hatte in der Konfig die MQTT Bridge aktiviert. Da ich diese aber nun wohl doch nicht benötige läuft nun alles wieder mit der Standart Konfig. Trotzdem versucht der CCU-Jack sich weiterhin minütlich zu verbinden, mit demetnsprechner Fehlermeldung.
`

ERROR | mqtt-bridge | Connecting to MQTT server on address tcp://192.168.178.44:1883 failed: dial tcp 192.168.178.44:1883: connect: connection refused
-- | -- | --

`

Ich habe erfolglos versucht das abzustellen mit:
- In der Konsole den CCU-Jack mit "stop" und danach "init" restartet
- in der CCU WebUI Zusatzsoftware CCU-Jack  "Neustart" 
- kompletter CCU3 Neustart

Kann ich das irgendwie wieder ausschalten ohne den CCU-Jack neu zu installieren?

**Comment by mdzio** [comment]
Bitte noch einmal prüfen, ob in der `ccu-jack.cfg` tatsächlich die MQTT-Bridge abgeschaltet ist. Wenn die Konfigurationsdatei geändert wird, während der CCU-Jack läuft, werden die Änderungen vom CCU-Jack wieder überschrieben.

**Comment by addy38** [comment]
Hast Recht, war wieder gesetzt, kann geschlossen werden..
