### ISSUE TITLE
MQTT Server Konfiguration

### ISSUE THREAD

**Issue by okionka** [mdzio/ccu-jack#111]
Vielen Dank für das tolle AddOn.
Ich habe mehrere Tasmota Geräte, welche ich an einem MQTT Broker auf RaspberryMatic anbinden möchte. 
Wie kann ich im ccu-jack den integrierten MQTT Broker konfigurieren?

* Benutzernamen & Passwörter für MQTT Devices, als auch MQTT Clients
* Persistenz für Messages und Logging auf einem USB Stick bzw. Datenbank

**Comment by mdzio** [comment]
Der CCU-Jack hat eine eigene Benutzerverwaltung (s.a. Web-UI zur Konfiguration). Diese wird auch für die Anmeldung an den eingebetteten MQTT-Server verwendet. Wenn keine Benutzer eingetragen sind, besteht Vollzugriff für alle.

Persistenz und Logging von MQTT-Nachrichten unterstützt der CCU-Jack nicht. Diese Funktionalität ist auch längerfristig bisher nicht geplant.
