### ISSUE TITLE
Erstinstallation auf CCU3

### ISSUE THREAD

**Issue by Raab1488** [mdzio/ccu-jack#114]
Hallo zusammen

Ich habe den CCU-Jack mit der neusten Firmware als Addon auf meiner CCU3 installiert. Ich habe ein Shelly 1PM und möchte die Messwerte abfragen und es daher über MQTT einbinden. 

Im Handbuch steht das es als Virtuelles Gerät hinzugefügt werden muss. Jedoch ist bei mir keine Möglichkeit, bei dem Menü Punkt „CCU Anbindung,  die Option der Virtuellen Geräte zu aktivieren. Mir geht nicht ganz hervor wie dies funktioniert. 

Ich bitte um Hilfe.

Vielen Dank

**Comment by mdzio** [comment]
Einfach links auf den Schalter neben "Virtuelle Geräte ativieren" klicken. Im [Handbuch ist eine entsprechende Abbildung](https://github.com/mdzio/ccu-jack/wiki/Anbindung-Shelly) zu finden.

**Comment by Raab1488** [comment]
> Einfach links auf den Schalter neben "Virtuelle Geräte ativieren" klicken. Im [Handbuch ist eine entsprechende Abbildung](https://github.com/mdzio/ccu-jack/wiki/Anbindung-Shelly) zu finden.

![jack](https://user-images.githubusercontent.com/122142384/211152301-4eb9c70e-b0af-422b-9bf6-ec98e874ba73.png)


Verzeihung, aber da befindet sich nichts.

Habe die Version 2.4 nun aufgespielt aber auch dort ist nichts zu finden.

**Comment by Raab1488** [comment]
> > Einfach links auf den Schalter neben "Virtuelle Geräte ativieren" klicken. Im [Handbuch ist eine entsprechende Abbildung](https://github.com/mdzio/ccu-jack/wiki/Anbindung-Shelly) zu finden.
> 
> ![jack](https://user-images.githubusercontent.com/122142384/211152301-4eb9c70e-b0af-422b-9bf6-ec98e874ba73.png)
> 
> Verzeihung, aber da befindet sich nichts.
> 
> Habe die Version 2.4 nun aufgespielt aber auch dort ist nichts zu finden.

Kleiner Nachtrag. Habe nun die Version 2.61 aufgespielt, jedoch mit dem selben Bild wie zuvor. Habe ich was vergessen zu machen ?

**Comment by mdzio** [comment]
Bitte einmal im Web-Browser die Taste F5 oder Strg und F5 drücken, damit die Web-Oberfläche vom CCU-Jack neu geladen wird.

**Comment by Raab1488** [comment]
... hatte zuvor es auf der CCU2 versucht, der Browser Cache war es ! Vielen Dank !

**Comment by Raab1488** [comment]
Nach der tollen Hilfestellung, dachte ich, ich könnte nochmal kurz weiter fragen. *Grins*

Ich habe nun 2 Shellys per MQTT eingebunden bekommen. Im MQTT Explorer kann man das ganz gut sehen und die Werte scheinen zu stimmen.

Ich habe weiter die Anleitung befolgt, ein neues Gerät angelegt, in die CCU eingebunden und dort die Zeilen mit der passenden Seriennummer angepasst. Leider bekomme ich die Werte nicht in der CCU angezeigt, auch schaltet das Relais nicht wenn ich es betätige. 

Ich bin für weitere Tipps sehr dankbar.

Vielen Dank !!

Hier noch 2 Bilder. 

![Screenshot 2023-01-08 220056](https://user-images.githubusercontent.com/122142384/211219086-d5bb2af9-963b-4cec-a1d7-b9aa40488400.png)
![Screenshot 2023-01-08 220635](https://user-images.githubusercontent.com/122142384/211219087-21f839f8-122a-41ab-9ba4-0f150de8a478.png)

**Comment by Raab1488** [comment]
Ich habe in der Anleitung noch das Bild gefunden wie der Shelly die MQTT Einstellungen bekommt. Dabei ist mir aufgefallen das bei seinem Namen noch das "shellies/" davor gesetzt werden muss. Sie waren von der Shelly Seite, aber auch von der CCU Seite aus mit dem MQTT Jack verbunden, konnten aber so aufgrund unterschiedlicher Instanzen nicht miteinander kommunizieren.

Vielen dank nochmal für die Hilfestellung!
