### ISSUE TITLE
Datenpunkt für Duty-Cycle der CCU

### ISSUE THREAD

**Issue by djiwondee** [mdzio/ccu-jack#115]
Hallo @mdzio,

vielen Dank für das tolle Add-On. Es funktioniert sehr gut! Ich habe eine Frage: gibt es einen Datenpunkt, der ähnlich/gleich WebUI der CCU auf der Startseite den Duty-Cycle aller angebundenen Devices bereitstellt:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/37173958/211197257-4fd70cfa-d61a-451e-96ea-96ce37314c11.png">

Oder müsste ich mir mir z. B. ein [CCU-Programm schreiben](https://homematic-forum.de/forum/viewtopic.php?t=35097), der die Aggregation aller  Duty-Cycle der einzelnen Devices in eine Systemvariable schreibt? 

Danke im Voraus für eine kurze Info dazu!

**Comment by Baxxy13** [comment]
Bei einer "echten CCU3" kann man das Funkmodul "freischalten".
Dann erscheint es als eigenständiges Gerät mit DUTY_CYCLE & CARRIER_SENSE Anzeige.
Das Gerät taucht dann auch im CCU-JACK mit den Datenpunkten auf.
["Freischalt-Anleitung"](https://homematic-forum.de/forum/viewtopic.php?f=31&t=64657&p=667178&hilit=carrier+sense#p636443)

Die Duty Cycle Anzeige auf der WebUI-Startseite bezieht sich nur auf den DC der CCU.
An den DC der einzeln Geräte kommt man nicht heran, es gibt maximal eine Servicemeldung wenn dieser zu hoch ist (und das Gerät damit für ca. 1h sämtliche Kommunikation einstellt).

**Comment by djiwondee** [comment]
Vielen Dank @Baxxy13. Das schaue ich mir auf jeden Fall an. Ich habe eine "originale/echte" CCU3.

Bringt mich allerdings zu der nächsten Frage: `system.Exec()`wird ja gerne als "instabil" und "unzuverlässig" in diversen Foren diskutiert und man sollte sich den [CUxD-Daemon](https://homematic-forum.de/forum/download/file.php?id=100919) installieren, um eine Alternative zu `system.exec()` zu haben?

**Comment by djiwondee** [comment]
Just heute erschienen: https://homematic-ip.com/sites/default/files/other_media/ccu3-changelog-3-67-10.pdf

> Erweiterungen / Änderungen
> [HMCCU-1035] : Für den CCU3 Coprozessor / RPI-RF-MOD gibt es jetzt ein Geräteobjekt. Damit können Statuswerte wie Duty Cycle und Carrier Sense dargestellt und in Programmen verwendet werden.

**Comment by Baxxy13** [comment]
Reicht ja auch. 
Mehr hätte das einmalig auszuführende Script auch nicht gemacht.
Aber schön das eQ-3 jetzt das Funkmodul "out-of-the-box" freischaltet.
