### ISSUE TITLE
Shelly Dimmer 2

### ISSUE THREAD

**Issue by Raab1488** [mdzio/ccu-jack#118]
Hallo,

Der Shelly Dimmer 2 kann mittels MQTT an die CCU gebunden werden. 

Jedoch sind nur Status Werte die Übermittelt werden ? 
Ein bedienen von der CCU Seite ist nicht möglich. Weder die Dimmwerte Einstellung noch das Ein/Aus schalten.

Alle Aktionen von der Shelly Seite bekommt die CCU jedoch mit.

Ist das so richtig ? Oder müssen weitere Einstellungen vorgenommen werden? 

Vielen Dank für die Hilfe

**Comment by mdzio** [comment]
Der Shelly Dimmer 2 sollte auch von der CCU aus ansteuerbar sein.

Du hast einen virtuellen Dimmerkanal im CCU-Jack angelegt? Wie ist das virtuelle Gerät parametriert?

**Comment by Raab1488** [comment]
Aktuell ist es so parametriert wie es in der Beschreibung steht.

Allerdings ist es nicht möglich gewesen den Präffix "shellies/" und den Vollständigen Namen zu verwenden. Da der Name bei der Shelly Oberfläche zu lang ist. 

![Screenshot 2023-01-14 151741](https://user-images.githubusercontent.com/122142384/212476566-7cecec4c-14a7-43df-bba6-cb447d76efcc.png)


Zusätzlich wollte ich den Verbrauch anzeigen lassen wie bei dem 1PM, ist das auch nur einen zusätzlichen Analogwertempfänger? Wie ist dort der Befehl ?

Gruß

**Comment by mdzio** [comment]
Wie sehen denn die vollständigen Topics im MQTT Explorer aus? Das doppelte shellies/ am Anfang wundert mich.

**Comment by Raab1488** [comment]
![Screenshot 2023-01-14 154447](https://user-images.githubusercontent.com/122142384/212477637-826b15a4-6c39-44a7-b20e-8f118b9f8ae3.png)

**Comment by mdzio** [comment]
Ich denk, dass **shellies/** nur einmal im Anfang vorkommen darf. Bitte einmal die Topic-Parameter im virtuellen Gerät anpassen.

**Comment by Raab1488** [comment]
![image](https://user-images.githubusercontent.com/122142384/212477861-052324a7-e185-4462-a585-929b89814735.png)


Habe ich angepasst, sodass nur ein mal Shellies dort steht.

Hier ist die Vollständige Topic anzeige, man sieht auch das Aufleuchten des Geräten, aber keine Änderung des Gerätes selbst

**Comment by mdzio** [comment]
Wie sehen die Topics und Nachrichten unterhalb von _light_ aus?

Du kannst auch in der _Konfiguration_ vom CCU-Jack das Logging auf DEBUG oder TRACE stellen und dann unter _Diagnose_ mal hineinschauen. Sind dort Warn- oder Fehlermeldungen? Die letzten Log-Meldungen können auch unter Adresse `https://<IP-CCU>:2122/~vendor/diagnostics/~pv` herunter geladen werden.

**Comment by Raab1488** [comment]
Zunächst hier die Vollständige topic. Die Diagnose kommt gleich

**Comment by mdzio** [comment]
Der Analogwertempfänger für _Power_ müsste folgendermaßen konfiguriert werden:
TOPIC: shellies/shellydimmer2-3C6105FDB09C/light/0/power
EXTRACTOR: ALL

Der Analogwertempfänger für _Energy_ müsste so konfiguriert werden:
TOPIC: shellies/shellydimmer2-3C6105FDB09C/light/0/energy
EXTRACTOR: ALL

**Comment by Raab1488** [comment]
Das Gerät :2 habe ich eigentlich gelöscht. 

Aber ja da ist in der tat eine Fehlermeldung 
![Screenshot 2023-01-14 171213](https://user-images.githubusercontent.com/122142384/212482411-599cc536-fb50-4757-a787-dd2e8f228014.png)

**Comment by Raab1488** [comment]
> Der Analogwertempfänger für _Power_ müsste folgendermaßen konfiguriert werden: TOPIC: shellies/shellydimmer2-3C6105FDB09C/light/0/power EXTRACTOR: ALL
> 
> Der Analogwertempfänger für _Energy_ müsste so konfiguriert werden: TOPIC: shellies/shellydimmer2-3C6105FDB09C/light/0/energy EXTRACTOR: ALL

Perfekt, das Funktioniert schon mal

**Comment by mdzio** [comment]
Den Log-Meldungen entnehme ich, dass sich noch eine andere Software mit dem CCU-Jack verbinden. Die verwendete ID ist HAP_CCU-Jack. Weißt Du welche das ist? Die Software sendet ungültige Antworten an den CCU-Jack, wodurch die Fehlermeldungen entstehen. 
Ich würde gern den CCU-Jack anpassen, sodass er über die ungültigen Antworten hinwegsieht, da sie keine Funktion einschränken. 
Könntest Du vielleicht eine Log-Datei erstellen, [wie im Handbuch beschrieben](https://github.com/mdzio/ccu-jack/wiki/Unterst%C3%BCtzung), und mir zur Verfügung stellen? Mit dem Log-Level TRACE werden die Rohdaten der Kommunikation mit der Fremd-Software angezeigt.

**Comment by Raab1488** [comment]
Hi

Der Port 9875 wird noch von dem Addon HAP für die HomeKit Anbindung verwendet wenn ich das richtig gesehen habe. 

Die Log Datei muss ich mittels Putty auslesen? Über den Browser ist es nicht möglich richtig ? 

Dann stelle ich sie heute Abend rein

**Comment by mdzio** [comment]
Die Fehlermeldung sollte in der nächsten Version vom CCU-Jack nicht mehr kommen (s.a. #120).

**Comment by mdzio** [comment]
Verwende mal bitte für das COMMAND_TOPIC: shellies/shellydimmer-{deviceid}/light/0/set
(anstatt: shellies/shellydimmer-{deviceid}/light/0/command)

**Comment by Raab1488** [comment]
mit dem "/set" funktioniert die Ansteuerung ! 

Scheinbar hat das HAP-Homekit Addon doch eine Auswirkung. Ich hatte sie nicht die ganze Zeit drauf erst seit kurzem nachdem ich die Shellys eingebunden habe. Seitdem funktioniert die Rückmeldung nicht mehr. 
Oder das Update 2.7.0?

Bei dem Shellys 1Plus wo nur ein Schalt Befehl da ist, wird der korrekte Zustand angezeigt. Bei dem Dimmer Aktualisiert er den Dimmwert nicht. Bei dem 1PM habe ich den Aktuellen Watt Verbrauch in ein Programm geschrieben, dass wenn es kleiner als 30 ist, aus geht. Hatte funktioniert, nun nicht mehr. 

Muss der Feedback_Topic Befehl auch angepasst werden?

Ich danke dir auf jeden fall für deine Hilfe und Ich hoffe ich kann auch dadurch dir bei Fehlerbehebungen nützlich sein.

**Comment by mdzio** [comment]
So sollte jetzt alles richtig konfiguriert sei. Im HomeMatic-Forum hatte jemand erfolgreich einen Shelly Dimmer angebunden. Ich weiß aber nicht mehr, wer das war.

Für Testzwecke solltest Du das HAP-Homekit Add-On mal entfernen.

**Comment by Raab1488** [comment]
Ich habe gestern Abend noch ein paar Tests gemacht. 

Das HAP - Addon habe ich runter geschmissen. Logischerweise kamen keine Fehlermeldungen mehr im Jack. Allerdings waren die Status Werte unverändert und habe sich nicht aktualisiert, auch nach einem Neustart der CCU und Jack dadurch. 

Danach habe ich die Jack Version 2.6.1 aufgespielt, die Aktualisierungen gehen wieder. Danach HAP aufgespielt, funktioniert weiterhin. 

Scheint als wäre in der Version 2.7.0 des Jacks was nicht in Ordnung. 

Vielen Dank für die Hilfe ! Ich denke damit können wir das hier schließen? Oder sollen wir noch was ausprobieren ?

**Comment by mdzio** [comment]
Ich habe die V2.7.0 mit den obigen Topics und Payloads getestet, und es hat alles funktioniert. Es wurde auch kein Fehler von anderen Anwendern gemeldet. Deshalb schließe ich mal diesen Eintrag.
