### ISSUE TITLE
Läuft eine der Installationsvarianten auf dem Tinkerboard 2?

### ISSUE THREAD

**Issue by andesse** [mdzio/ccu-jack#119]
Hallo,

habe leider keine Infos dazu gefunden.
der Titel sagt es schon, läuft dies auch auf dem Tinkerboard 2?
Welche Installationsdatei wäre auszuwählen?

**Comment by mdzio** [comment]
Ich habe es jetzt auch [im Wiki](https://github.com/mdzio/ccu-jack/wiki/Download) vermerkt.
