### ISSUE TITLE
Wertänderungen an einen externen MQTT-Server schicken

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#12]
Der CCU-Jack könnte um eine MQTT-Bridge erweitert werden. Diese abonniert alle Topics des eingebetteten MQTT-Server und schickt die Wertänderungen an einen externen MQTT-Server.

Entsprechend ist auch die andere Richtung denkbar: Der CCU-Jack abonniert alle Wertänderungen von einem externen MQTT-Server und dupliziert sie auf den eingebetten Server.

**Comment by dersimn** [comment]
## Workaround when using Mosquitto Broker

- `10.1.1.150`: CCU in VM with CCU-Jack installed
- `10.1.1.50`: Mosquitto Broker

Adding to `mosquitto.conf`:

    # MQTT Bridge
    connection ccu-broker
    address 10.1.1.150
    topic # in  0 ccu_device/status/ device/status/
    topic # out 0 ccu_device/set/    device/set/

This bridges all `device/…` topics from CCU-Jack to your "main" Broker on `ccu_devices/…`.

You can even simplify this configuration, but I like to seperate between the in/out direction for the status/set topics as a failsafe.

**Comment by martgras** [comment]
Wie wäre es wenn man statt dessen einen externen mqtt broker nutzen könnte und der interne dann gar nicht gestartet wird?

**Comment by mdzio** [comment]
Da diese Funktionalität bereits in anderen Brokern (z.B. Mosquitto, HiveMQ, EMQ X) zur Verfügung steht, lohnt es nicht, hier Zeit zu investieren.
