### ISSUE TITLE
Home Assistant MQTT Autodiscovery

### ISSUE THREAD

**Issue by robgru** [mdzio/ccu-jack#121]
Hallo,
es wäre sehr cool, wenn CCU-Jack Autodiscovery für Home Assistant unterstützen würde.
Dies würde für den User sehr viel Konfigurationsaufwand ersparen und man wäre nicht mehr so von Home Assistant Integrationen abhängig.

**Comment by mdzio** [comment]
Die Umsetzung der Autodiscovery-Funktionalität ist mit viel Aufwand verbunden. Deswegen wird sie so schnell nicht kommen.
(siehe auch Eintrag #7 ).
