### ISSUE TITLE
Fehler in der Anleitung zur Anbindung eines Shelly Dimmer 2

### ISSUE THREAD

**Issue by Daeresh** [mdzio/ccu-jack#123]
Ich habe gerade meine ersten Gehversuche mit CCU-Jack gemacht. Ein tolles Tool, welches die Shellies wirklich toll in Homematic integriert!

Ich habe beim ersten Einrichten mit meinem Shelly Dimmer 2 recht lange gebraucht bis ich herausgefunden habe, daß für den Shelly Dimmer "**2**" die folgenden in der Anleitung genannten Parameter nicht stimmen:

Falsch laut Anleitung:
COMMAND_TOPIC | shellies/shellydimmer-Seriennr./light/0/set
FEEDBACK_TOPIC | shellies/shellydimmer-Seriennr./light/0/status

Richtig ist:
COMMAND_TOPIC | shellies/shellydimmer**2**-Seriennr./light/0/set
FEEDBACK_TOPIC | shellies/shellydimmer**2**-Seriennr./light/0/status

Ohne die Angabe der **2** hinter shellydimmer funktionieren die MQTT Befehle nicht.
Wie die Befehle für die shellydimmer 1 lauten weiß ich nicht. Ich vermute daß hier einfach wie in der Anleitung genannt "shellydimmer" ohne eine Zahl verwendet werden muss.

Es wäre toll, wenn Du das in der Anleitung ergänzen könntest. Damit andere nicht über das Problem stolpern.

Außerdem wäre es hilfreich einen kurzen Hinweis zu bekommen, wo sich die Seriennummer befindet.
Auf der Shelly Page -> Settings -> Device Info -> Device ID (der alphanumerische Code)

Da auf der Shelly Page neben dem Alphanumerischen Code noch ein Zahlencode in Klammern steht, habe ich erst durch Versuche herausbekommen welcher von den beiden die Seriennummer ist.

Viele Grüße
Wolfram

![Shelly Dimmer 2 in Homematic über CCU-Jack und MTTQ ansprechen](https://user-images.githubusercontent.com/123845048/215296978-ffe1bf6f-3a20-48fd-ad49-8f591c3e69bc.png)

**Comment by mdzio** [comment]
Vielen Dank für den ausführlichen Verbesserungsvorschlag zur Dokumentation. Ich habe die [Seite im Handbuch](https://github.com/mdzio/ccu-jack/wiki/Anbindung-Shelly) entsprechend angepasst.
