### ISSUE TITLE
Zeige auch die von extern angelegten Topics im Navigator

### ISSUE THREAD

**Issue by swenp76** [mdzio/ccu-jack#124]
Ich publishe via RedMatic diverse zusätzliche Topics im CCU-Jack.
Im MQTT-Explorer z,.B. sind sie dann sichtbar und auch von anderen Apps sind sie lese/schreibbar.
Im Navigator des CCU-Jack tauchen sie aber nicht auf. Könnte man das ändern, so dass kein zusätzliches Tool mehr notwendig ist um alle verfügbaren Topics auf dem Server zu sehen?
P.S. Danke für den Jack!

**Comment by mdzio** [comment]
In der Web-UI des CCU-Jacks _könnte_ auch ein MQTT-Client eingebaut werden. Allerdings ist dies sehr aufwändig. Da die Entwicklerzeit sehr begrenzt ist, muss erst einmal ein externes Werkzeug verwendet werden.
