### ISSUE TITLE
Zeitstempel unter /~vendor/refresh

### ISSUE THREAD

**Issue by ptweety** [mdzio/ccu-jack#125]
Hi,

ich wunderte mich gerade über den unter `/~vendor/refresh` angezeigten Zeitstempel. Ein Abruf über die API auf `/~vendor/refresh/~pv` liefert dann etwa sowas:

```
{
  ts: -6795364578871,
  v: false,
  s: 0,
}
```

Format | ---
-- | --
GMT | Fri Aug 30 1754 22:43:41 GMT+0000
Your Time Zone | Fri Aug 30 1754 23:37:09 GMT+0053 (Mitteleuropäische Sommerzeit)
Relative | 268 years ago

Kann das jemand reproduzieren?

**Comment by mdzio** [comment]
Ja, ich kann das reproduzieren. Das soll natürlich nicht so sein.
