### ISSUE TITLE
MQTT Energiemessung - Energie-Zähler zeigt identische Werte auf mehreren Geräten an

### ISSUE THREAD

**Issue by dega2** [mdzio/ccu-jack#133]
Ich habe drei virtuelle HM-ES-PMSw1-PI erstellt, hinter denen Shelly Plug S per MQTT senden. 
Die drei virtuellen Geräte habe jeweils einen Kanal "MQTT Schaltaktor mit Rückkanal" und einen Kanal "MQTT Energiemessung".
Der "MQTT Energiemessung"-Kanal erhält über MQTT-Topics:
![image](https://github.com/mdzio/ccu-jack/assets/27890269/f37b66de-5c78-4aad-ad92-4df8bb0c5acf)

Soweit läuft alles. Ich erzeuge mir ein Diagramm mit den Leistungswerten, da ich erfassen wollte, wie hoch der Verbrauch unserer Kühl- und Gefrierschränke ist. Das Diagram sieht gut aus und ich sehe wann der Kompressor Energie verbraucht.
Was merkwürdig ist und wie ein Bug aussieht ist, dass alle drei "Energie-Zähler - Gerät" und "Energie-Zähler - Zentrale" auf der CCU-Geräte Seite die gleichen Werte anzeigen. Es sieht so aus, als ob alle drei Geräte summiert werden oder nur die Energie eines der Geräte gezählt wird und für alle angezeigt wird oder, was besonders merkwürdig wäre, immer fix 2023.00 Wh anzeigt.
Ich habe auch einen echten HM-ES-PMSw1-Pl, der nicht betroffen ist und unabhängige Werte anzeigt. Daher vermute ich, dass hier das Problem bei den CCU-Jack Geräten liegt.

**Comment by mdzio** [comment]
Ich werde das noch einmal testen.
Die TOPICs in den drei Messwertkanälen sind aber schon unterschiedlich konfiguriert?

**Comment by Baxxy13** [comment]
Ich habe auch 2 JACK-HM-ES-PMSw1-Pl angelegt.
Diese werden aber durch komplett unterschiedliche Topics "gesteuert". (1x von Tasmota, 1x SDM120 MQTT Stromzähler)
Das funktioniert hier völlig korrekt und unabhängig voneinander.

**Comment by dega2** [comment]
Für die Anzeige der Spannung, Strom und Leistung ist das bei mir auch der Fall, allerdings zeigten die Energiezähler aller Geräte permanent 2.02 kWh. 
![image](https://github.com/mdzio/ccu-jack/assets/27890269/ab614960-0818-43c4-bc1d-1ac43a73e3dc)

Hier das Json des MQTT Pakets:
![image](https://github.com/mdzio/ccu-jack/assets/27890269/9610118e-a1ce-4051-b8fb-4f45a9af9c38)
Ich habe mal zum testen auf Today umgestellt. Hier wurde nun 0.66 Wh angezeigt, was soweit okay wäre - Wh zu kWh ist halt der Faktor 1000. Ist aber der richtige Wert und auch unabhängig.
Nun habe ich mir nochmal die Doku zu Gemüte geführt und das POWERMETER|ENERGY_COUNTER_EXTRACTOR auf Template umgestellt sowie POWERMETER|ENERGY_COUNTER_PATTERN auf {{ mul (parseJSON .).ENERGY.Total 1000 }}
Seit dem bekomme ich für Total nun ebenfalls den korrekten Wert angezeigt (mit Umrechnung auf Wh)
