### ISSUE TITLE
Neues Update

### ISSUE THREAD

**Issue by Raab1488** [mdzio/ccu-jack#134]
Hi mdzio,

Wir hatten im Januar mal über ein zukünftiges Update gesprochen wo die Fehlermeldung, die durch das HAP Homekit Addon ausgelöst wird, ignoriert werden soll.

Siehe Bild.

Gibt es da Neuigkeiten wann ich mit diesem Update rechnen kann?

Liebe Grüße Raab
![Screenshot 2023-06-30 150503](https://github.com/mdzio/ccu-jack/assets/122142384/23c50e61-c5a4-420e-80aa-4ca7f812fd8d)

**Comment by mdzio** [comment]
Es kommt heute abend.
