### ISSUE TITLE
Frage: Wochenprogramm de-/aktivieren

### ISSUE THREAD

**Issue by djiwondee** [mdzio/ccu-jack#136]
Hallo @mdzio 

gibt es eine Möglichkeit, bei eingestellten Wochenprogrammen diese von Automatisch auf Manuell und umgekehrt zu setzen?

![image](https://github.com/mdzio/ccu-jack/assets/37173958/492d9882-d59c-4c14-bcf7-eef7dc9a9e48)

Ich habe es ein paar Versuche über z. B.
`device/set/003***********/8/WEEK_PROGRAM_TARGET_CHANNEL_LOCK`

gemacht. Das hat aber nicht funktioniert. Hintergrund: ich möchte konfigurierte, aktive Wochenprogramme z. B. bei An-/Abwesenheit de-/aktivieren.

Danke für einen Hinweis.

**Comment by mdzio** [comment]
Ist denn die Information im Navigator der Web-UI des CCU-Jacks zu finden? Eventuell ist sie auch Bestandteil vom Masterparamset eines Gerätes. Masterparamsets sind in der Variablen $MASTER zu finden.

**Comment by RolandBrezinaDVAG** [comment]
Hallo @Baxxy13,
des werde ich ausprobieren! Vielen Dank für die Recherche. 

> ... die beiden möglichen Werte kommen aus einer Binärmaske

Da bin ich bei bißchen Recherche im Forum auch schon draufgestoßen

> Der Modus steht im flüchtigen Speicher des Gerätes. Ist das Gerät kurz spannungslos steht danach alles wieder auf AUTO.

Das wäre für mich sogar ein gewünschter Nebeneffekt. Der Default soll unbedingt so sein: AUTO

> Nicht von den "Kullerchen" im Wochenprogramm-Kanal verwirren lassen, die sind mit 3.69.7 buggy

Danke für die Info. Den Bug habe ich auch schon festgestellt, allein der geplante Fix ist mir neu. Ich bin beim [eq3-Support schon mal abgeblitzt](https://homematic-forum.de/forum/viewtopic.php?f=58&t=78280#p760788), mit der Begründung, ich hätte custom Software auf der CCU. Deshalb habe ich mir Feedback/Meldung dazu gespart...

Nochmals Danke!

**Comment by mdzio** [comment]
Ich denke, dass der Eintrag mit der letzten Antwort geschlossen werden kann.

**Comment by djiwondee** [comment]
Hallo @Baxxy13, @mdzio  
jetzt hätte ich aber doch nicht mal ein Frage: Wie lässt sich denn der RAW-Wert in einen JSON Key/Value-Pair "übersetzen".

Hintergrund: ich möchte mittels Node-red und der MQTT-Node den Modus ändern können 
![image](https://github.com/mdzio/ccu-jack/assets/37173958/6bea7668-398b-4bb6-a54e-68b34bb59f6c)

Weder der Payload als String `"WPTCLS=7,WPTCL=1"` als auch per JSON in der Form
```
{
    "WPTCLS": 7,
    "WPTCL": 1
}
```
funktionieren damit.

Was mach CCU-Jack aus dem Payload?

**Comment by mdzio** [comment]
Dann probier bitte mal:
```
{"v":"WPTCLS=7,WPTCL=1"}
```
Oder:
```
WPTCLS=7,WPTCL=1
```
(Ohne Anführungszeichen)

**Comment by RBrzDVAG** [comment]
Hallo @mdzio 

probiert hatte ich schon `msg.payload.v = "WPTCLS=7,WPTCL=1"`, was auch nicht funktionierte. Aber das hier tut es: 

`msg.payload = {"v":"WPTCLS=7,WPTCL=1"}`

Vielen Dank!
