### ISSUE TITLE
STATE ändert sich nicht

### ISSUE THREAD

**Issue by thommyDD** [mdzio/ccu-jack#137]
Hallo zusammen,

vielen Dank zunächst einmal für das tolle PlugIn!
Leider habe ich bei der Benutzung ein kleines Problem: Wenn ich von einer Steckdose den State mittels `curl http://localhost:2121/device/<DEVICE_ID>/3/STATE/~pv` (Kanal 3)abfrage, bekomme ich immer `false` zurück. Die Steckdose ändert ihren Zustand korrekt, über das PlugIn wird der Status offenbar nicht korrekt erreicht. 

Vielen Dank für eure Unterstützung.

**Comment by mdzio** [comment]
Handelt es sich um eine HmIP-Steckdose? Diese besitzt 3 virtuelle Kanäle. Eventuell fragst Du also einen virtuellen Kanal ab. Es sollte der Kanal "Statusmitteilung Schaltausgang" (i.d.R. der Kanal 2) verwendet werden.

**Comment by mdzio** [comment]
Ich schließe mal diesen Eintrag. Wenn das Problem weiterhin besteht, kann er wieder geöffnet werden.
