### ISSUE TITLE
Virtuelle Geräte: Temperatursensor innen

### ISSUE THREAD

**Issue by MoLiNaSa** [mdzio/ccu-jack#148]
ich möchte gerne ein Thermometer (Daten über MQTT) mit einem HmIP Thermostat verknüpfen. Die IST-Werte der Thermostate sind nicht ideal ohne Raumthermometer. 
Derzeit finde ich in CCU-Jack nur HmIP-STHO für Temperatur, aber eines für innen, welches am liebsten mit HmIP-eTRV-2 zusammenarbeiten würde, wäre super klasse.
Oder kann ich z.B. das HmIP-STH als virtuelles Gerät selbst erstellen? Wenn ja - wie und wo?

Super Tool - vielen Dank!

**Comment by mdzio** [comment]
Eine Direktverknüpfung der virtuellen CCU-Jack-Geräte mit realen HM-IP-Geräten ist technisch nicht möglich. Dafür muss immer ein Programm auf der CCU erstellt werden. Ich weiß aber nicht, ob dem HmIP-eTRV-2 für die Regelung die aktuelle Raumtemperatur über ein Programm übermittelt werden kann. Eventuell müsste dies mal im [HM-Forum](https://homematic-forum.de/forum/) nachgefragt werden.

Das Icon für HmIP-STH kann ich in der nächsten Version hinzufügen.
