### ISSUE TITLE
MQTT: Auslösen des Lesens einer Systemvariable auch bei interner Aktualisierung durch CCU

### ISSUE THREAD

**Issue by ptlrk** [mdzio/ccu-jack#15]
Schon jetzt werden Änderungen an Systemvariablen bereits nach 300/400 ms gelesen und an Subscriber publiziert, wenn sie von einem (externen) MQTT-Client geändert wurden.
Bei internen Änderungen durch die CCU-Logikschicht erfolgt das erst nach dem zyklischen Lesen (1/s) der mit "MQTT" gekennzeichneter Systemvariablen. Bei einer größeren Anzahl kann es daher lange dauern, z.B. 60 Sekunden bei 60 MQTT-Variablen, bis die Änderung am MQTT-Subscriber ankommt.
Im Gegensatz dazu kommen Status-Änderungen von Geräten nahezu "sofort" an. Wenn nun die Zustände mehrerer Geräte in einer Systemvariable aggregiert werden ("Eine Tür ist offen"), führt das vorübergehend zu irritierenden Inkonsistenzen auf der Anzeige (alle Türen werden einzeln als "Geschlossen" angezeigt, die Systemvariable zeigt aber "offen" an), solange bis CCU-Jack die Liste abgearbeitet hat.

Wäre es möglich, geänderte Systemvariablen auch dann zu lesen bzw. publizieren, wenn sie von innerhalb der CCU geändert wurden?

**Comment by mdzio** [comment]
Das ist zurzeit technisch nicht möglich. Die Logikschicht der CCU (ReGaHss) bietet diese Funktionalität nicht an. Dies wird bereits auch in jens-maus/RaspberryMatic#28 diskutiert. Gerätedatenpunkte bieten diese Funktionalität hingegen. 

Sicherlich kann diskutiert werden, wann Systemvariablen gelesen werden sollen. Die Zykluszeit könnte angepasst werden. Es könnte Gruppen mit verschiedenen Zykluszeiten gebildet werden. Oder das Auslesen kann durch einen Gerätedatenpunkt (z.B. der letzte virtuelle Taster BidCoS-RF:50) angestoßen werden. Dann müsste aber nach dem Setzen einer Systemvariable noch der Taster angestoßen werden.

**Comment by ptlrk** [comment]
Hab schon so etwas befürchtet. 
Idee: Ein Script auf der CCU ist mit allen fraglichen SysVars auf "Aktualisierung" verknüpft, holt sich die ID der auslösenden SysVar, speichert sie in einer "Verweis-SysVar", triggert einen Virtual Key der Zentrale und damit ein Event für CCU-Jack. Der kann sich die ID der auslösenden SysVar aus der Verweis-SysVar holen und die auslösende Variable damit gezielt auslesen. Die CPU-Last bleibt klein, weil man man nicht immer alle abfragen müsste. Die Zykluszeit von 1 s wurde sicher nicht umsonst so gewählt. Danach setzt CCU-Jack die Verweis-Sysvar wieder auf Null. 
Weiß noch nicht, was passiert, wenn sich mehrere Variablen zu kurz hintereinander ändern. Evtl. kann man Aufrufe vewerfen bis CCU-Jack die letzten Daten abgeholt und die Verweis-Variable wieder auf Null gesetzt hat. Dabei könnten schnelle Änderungen verlorengehen bis der nächste Rundumschlag ausgeführt wird.

**Comment by ptlrk** [comment]
Schließne war aus Versehen, sorry!

**Comment by mdzio** [comment]
Der Vorschlag mit der _Verweis-SysVar_ ist meines Erachtens zu kompliziert. Wenn aber das Lesen einer konfigurierbaren Gruppe an Systemvariablen bei Aktualisierung eines Gerätedatenpunktes angestoßen werden kann, deckt dies schon die meisten Anwendungsfälle ab. Es könnten auch mehrere Gruppen mit mehreren Gerätedatenpunkten verknüpft werden.

Ich habe ein neues Issue #16 aufgemacht, da die ursprüngliche Anforderung zurzeit technisch nicht möglicht ist.
