### ISSUE TITLE
Tasmota mit Temperatursensoren in CCU-Jack einbinden

### ISSUE THREAD

**Issue by Wichtelmann112** [mdzio/ccu-jack#151]
Ich versuche mich gerade mit der Übernahme von Temperaturen (4xDS18B20 an einem tasmota) in meine RaspberryMatic.
Ich habe 
-MQTT auf dem Tasmota eingerichtet
-im CCU-Jack ein Virtuells Gerät mit 4x MQTT Analogwertempfänger eingerichtet
-das virtuelle Gerät in der RM eingebunden

Nun komme ich mit den Daten der Sensoren nicht weiter. Diese zeigen ihre Werte im Explorer

`{"Time":"2023-10-28T09:01:21","DS18B20-1":{"Id":"082211090FEB","Temperature":37.2},"DS18B20-2":{"Id":"0822112C8A94","Temperature":37.9},"DS18B20-3":{"Id":"3DE1D4432441","Temperature":42.0},"DS18B20-4":{"Id":"3DE1D443E76C","Temperature":39.6},"TempUnit":"C"}
`
Welche parameter muss ich nun in der RM bei dem virtuellen Gerät für die 4 Kanäle eingeben?
-ANALOG_INPUT_TRANSMITTER\|TOPIC
-ANALOG_INPUT_TRANSMITTER\|PATTERN

**Comment by mdzio** [comment]
Das TOPIC wird im MQTT-Explorer bei der Nachricht mit angegeben. EXTRACTOR auf TEMPLATE stellen. REGEXP_GROUP ist egal. 

PATTERN für 1. Sensor: `{{ index (parseJSON .) "DS18B20-1" "Temperature" }}`

PATTERN für 2. Sensor: `{{ index (parseJSON .) "DS18B20-2" "Temperature" }}`

usw.

Hinweis: Nach dem Speichern stellt die CCU das obige PATTERN wie folgt dar: `{{ index (parseJSON .) &#34;DS18B20-1&#34; &#34;Temperature&#34; }}` Die CCU mag keine " und schreibt diese lieber als `&#34;` Das ist aber dasselbe.

[Siehe auch im HomeMatic-Forum.](https://homematic-forum.de/forum/viewtopic.php?f=85&t=80351)
