### ISSUE TITLE
Anbindung CCU mit CCU-Jack funktioniert nicht

### ISSUE THREAD

**Issue by guenter-ms** [mdzio/ccu-jack#153]
Hallo Mathias,

leider gelingt mir die connection zur CCU nicht. Ich möchte die CCU-Jack Integration gerne nutzen, bekomme aber die Verbindung nicht hin.

Alle Details sind unter https://homematic-forum.de/forum/viewtopic.php?f=85&t=80408&p=782964#p782964 beschrieben.

Z.I.: Ich habe das parallel auch hier an ptweety berichtet: https://github.com/ptweety/node-red-contrib-ccu/issues/12 aktuell noch keine Reaktion

Würde mich sehr freuen, wenn du da mal reinguckst.

Viele Grüße
guenni

**Comment by mdzio** [comment]
Kann es sein, dass gar keine virtuellen Geräte im CCU-Jack aktiviert sind? 

(s.a. Forum)

**Comment by guenter-ms** [comment]
Hi Mathias,

KORREKT!

Damit ist die Fehlermeldung weg.

Aber ich verstehe jetzt ehrlich nicht mehr das Funktionsprinzip. Vielleicht liege ich da falsch:

Ich lebe in der Welt, dass der CCU-Jack auf der Raspberrymatic einen alternativen Zugriff auf die Geräte und Systemvariablen der CCU bietet mit den genannten Vorteilen, siehe screenshot.

Und deshalb hatte ich ptweety/nodered-contrib-ccu installiert und CCU-Jack als Interface gecheckt. Aber genau darüber bekomme ich keine Daten.

Wo liegt mein Denkfehler?

Gruß Guenni
 





Am 03.11.2023 um 11:50 schrieb Mathias ***@***.***>:


Kann es sein, dass gar keine virtuellen Geräte im CCU-Jack aktiviert sind?

(s.a. Forum)

**Comment by mdzio** [comment]
nodered-contrib-ccu verwendet die vorhandenen Schnittstellen der CCU (XML-RPC, RegaHss) um mit der CCU zu kommunizieren. CCU-Jack ist dort nur eine weitere Schnittstelle für Geräte. Dies wird aber nur benötigt, wenn auch virtuelle Geräte im CCU-Jack verwendet werden.

[node-red-contrib-ccu-jack](https://github.com/ptweety/node-red-contrib-ccu-jack) hingegen benutzt nur den CCU-Jack für die Anbindung.

**Comment by guenter-ms** [comment]
Hallo Mathias,

vielen Dank! Jetzt habe ich es kapiert. 

Hilfreich wäre es, in der Doku (Anwenderhandbuch?) die Unterschiede deutlich zu machen:
-nodered-contrib-ccu
-ptweety/nodered-contrib-ccu
-nodered-contrib-ccu-jack 

contrib-ccu-jack werde ich jetzt mal testen, muss aber erst einmal sehen, wie ich den installieren kann, da er in der nodered Palette nicht angeboten wird.

Was den Mehrwert von virtuellen Geräten angeht, bin ich mir noch unsicher, da es die ja bereits mit cuxd gibt. Ich schau mit das mal näher an.

In every case: Vielen Dank für Deine tolle Arbeit.
Guenni
