### ISSUE TITLE
Integration Türschlossantrieb

### ISSUE THREAD

**Issue by josp666** [mdzio/ccu-jack#154]
Hallo,
ich wollte mal leise nachfragen ob es möglich ist den Türschlossantrieb nachzubilden.
Ich habe den Antrieb und den Türkontakt von Nuki. Beide sind bereits mit CCU-Jack und MQTT an die CCU angebunden nur leider beim Antrieb über den Umweg Homematic IP Multi IO Modulpatine - 4x4.
Das macht es optisch und von der Funktion her nicht ganz so optimal.
Vielen Dank schon mal.
Beste Grüße Jörg

**Comment by Baxxy13** [comment]
Warum hängst du dich nicht an #132 dran?
Da werden noch "Pro's" gesucht.

**Comment by josp666** [comment]
Hab ich gemacht, Danke für den Hinweis.

**Comment by mdzio** [comment]
Ich schließe mal den Eintrag, da es sich um ein Duplikat zum #132 handelt.
