### ISSUE TITLE
Zugriff auf CCU-Schnittstellenprozesse erst später beim Startvorgang möglich

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#156]
Mit der aktuellen RaspberryMatic-Version wurden folgende Fehlermeldungen beobachtet:
```
2023-11-05 12:14:20 ERROR v-devices List devices failed on 127.0.0.1:9292/bidcos, interface ID CCU-Jack_java: HTTP request failed on 127.0.0.1:9292/bidcos with code: 503 Service Unavailable
```

Fehlermeldung ist also: `503 Service Unavailable`.

Die Funktion vom CCU-Jack wird dadurch nicht beeinträchtigt.

[Eine Erklärung ist im Forum zu finden.](https://homematic-forum.de/forum/viewtopic.php?f=85&t=80458#p783589)

Unklar ist noch, wie genau festgestellt werden kann, ab wann die Schnittstellenprozesse tatsächlich zur Verfügung stehen. Der _HMIP-Server_ setzt beispielsweise ein `init`-Aufruf ab, bevor er selbst für die Callbacks erreichbar ist.

PS: `init`-Aufrufe sollten mit INFO-Level ins Log geschrieben werden, damit sie mit dem Standard-Log-Level sichtbar sind.

Edit: Ursache `EOF` entfernt.

**Comment by Baxxy13** [comment]
Die EOF - Meldungen haben eine andere Ursache.
Ich hatte die gestern fälschlicherweise mit gepostet weil ich mir dessen noch nicht bewusst war.

Das "Startup-Problem" zeigt sich nur so:
`2023-11-06 13:37:28|ERROR  |v-devices      |List devices failed on 127.0.0.1:9292/bidcos, interface ID CCU-Jack_java: HTTP request failed on 127.0.0.1:9292/bidcos with code: 503 Service Unavailable`

**Comment by mdzio** [comment]
Eventuell kann die Port-Änderung in go-hmcch/itf/vdevices/Handler.Init abhängig von einer Installation auf der CCU gemacht werden.

**Comment by Baxxy13** [comment]
Die Sperre erfolgt über den lighttpd, nicht über die Firewall.
"Freigegeben" wird erst ganz am Ende des Bootvorganges nach dem Start der AddOns.
Siehe: https://github.com/jens-maus/RaspberryMatic/commit/e971d75af79f1d073609fbd6133e4923107ff01a

**Comment by mdzio** [comment]
[Bitte mal V2.8.1-beta.2 testen.](https://github.com/mdzio/ccu-jack/releases/tag/v2.8.1-beta.2)

**Comment by Baxxy13** [comment]
Sieht soweit gut aus. 
Keine ERROR-Meldung mehr beim Systemstart der RaspberryMatic.
