### ISSUE TITLE
Keine Warnmeldung, wenn die CCU "setReadyConfig" aufruft

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#157]
Es sollte eine leere Implementierung dieser Funktion erstellt werden, damit keine Warnungen ins Log geschrieben werden.

Beispielfehlermeldung:
```
2023-11-05 11:26:53	WARNING	xmlrpc-server	Sending error response to 127.0.0.1:38858: Unknown method: setReadyConfig
```

**Comment by Baxxy13** [comment]
mit der V2.8.1-beta.2 sehe ich die Warnung immer noch:

`2023-11-15 15:15:04 | WARNING | xmlrpc-server | Sending error response to 127.0.0.1:41356: Unknown method: setReadyConfig`

**Comment by mdzio** [comment]
Anscheinend muss setReadyConfig in der CCU-Jack Logik-Schicht implementiert werden und nicht im Schnittstellenprozess für die virtuellen Geräte.
