### ISSUE TITLE
Which release for Pi Zero 2 W

### ISSUE THREAD

**Issue by sebhro** [mdzio/ccu-jack#159]
Which of the two releases ccu-jack-ccu3-rm-rp2+3-2.8.0.tar.gz or ccu-jack-rm-rp0+1-2.8.0.tar.gz should I choose for the Raspberry Pi Zero 2W?

**Comment by mdzio** [comment]
The Raspberry Pi Zero 2 W has the same CPU type as the Pi 2 and 3 ([see Table on Wikipedia](https://de.wikipedia.org/wiki/Raspberry_Pi)). You can therefore use ccu-jack-ccu3-rm-rp2+3-x.y.z.tar.gz.
