### ISSUE TITLE
Enhancement: Servicemeldungen 

### ISSUE THREAD

**Issue by noppingen** [mdzio/ccu-jack#166]
Unter /notification/ vielleicht?

**Comment by mdzio** [comment]
Die aktiven Service-Meldungen können über bereits vorhandene Gerätedatenpunkte ermittelt werden.

Beispiel-Datenpunkte für Service-Meldungen:
* UNREACH
* CONFIG_PENDING

Datenpunkte für Service-Meldungen werden an der Eigenschaft _flags_ erkannt. Wenn dort das 4. Bit gesetzt ist, handelt es sich um eine Service-Meldung. Dies ist z.B. bei dem Wert 9 der Fall.

Eigenschaften eines UNREACH-Datenpunktes:
![image](https://github.com/mdzio/ccu-jack/assets/24684496/7edd46da-24f3-4110-918f-f5b911e58592)

**Comment by noppingen** [comment]
Dankeschön und schöne Weihnachten!
