### ISSUE TITLE
Anbindung von shelly plus add-on

### ISSUE THREAD

**Issue by hflath** [mdzio/ccu-jack#167]
wie kann ich den shelly plus add on in meine homematic einbinden.
finde diese Einstellungen nicht.
bitte um Info.
![grafik](https://github.com/mdzio/ccu-jack/assets/153434707/fe0aeecd-f00e-41bb-8761-ccb686cdf324)

Danke

**Comment by Baxxy13** [comment]
Geht's nur um die Temperatur?
Dann würde ich als Jack-Gerät einen STHO mit Kanal "MQTT-Temperatursensor" nehmen.

Da es hier leider nur einen Screenshot gibt musste ich abtippen, also speziell das Topic nochmal auf Korrektheit prüfen.

Einstellungen Jack-STHO:

CLIMATE_TRANSCEIVER|TEMPERATURE_TOPIC: `shellyplus1pm-e465b8930ed4/status/temperature:100`
CLIMATE_TRANSCEIVER|TEMPERATURE_PATTERN: `"tC"`
CLIMATE_TRANSCEIVER|TEMPERATURE_EXTRACTOR: `AFTER`

Das sollte es gewesen sein. 😉

**Comment by hflath** [comment]
Super Danke für die Info,

jetzt funktioniert es.

 

Danke

 

Herold Flath

Lettenstraße 25

A 4523 Neuzeug

Tel.: +43 664 2138329

Mail: ***@***.***

 

Von: Baxxy13 ***@***.***> 
Gesendet: Samstag, 6. Jänner 2024 18:45
An: mdzio/ccu-jack ***@***.***>
Cc: hflath ***@***.***>; Author ***@***.***>
Betreff: Re: [mdzio/ccu-jack] Anbindung von shelly plus add-on (Issue #167)

 

Geht's nur um die Temperatur?
Dann würde ich als Jack-Gerät einen STHO mit Kanal "MQTT-Temperatursensor" nehmen.

Da es hier leider nur einen Screenshot gibt musste ich abtippen, also speziell das Topic nochmal auf Korrektheit prüfen.

Einstellungen Jack-STHO:

CLIMATE_TRANSCEIVER|TEMPERATURE_TOPIC: shellyplus1pm-e465b8930ed4/status/temperature:100
CLIMATE_TRANSCEIVER|TEMPERATURE_PATTERN: "tC"
CLIMATE_TRANSCEIVER|TEMPERATURE_EXTRACTOR: AFTER

Das sollte es gewesen sein. 😉

**Comment by mdzio** [comment]
Da das Problem gelöst ist, schließe ich mal diesen Eintrag.
