### ISSUE TITLE
MQTT: Unterstützung für WebSocket-Protokoll

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#17]
Damit Web-Applikationen im Browser sich über MQTT mit dem CCU-Jack verbinden können, muss eine Unterstützung für WebSockets eingebaut werden.

**Comment by ManniAT** [comment]
Bist du da noch am Arbeiten, oder "ruht" das Projekt?

**Comment by pburgmer** [comment]
Ich könnte dieses Feature immer noch sehr gut gebrauchen. 
Ich würde gerne etwas beisteuern aber leider kann ich kein Go und habe bisher keine Zeit gehabt mit einzuarbeiten. Kann ich irgendwie anders bei der Umsetzung helfen? Ich hatte im Sommer schon mal ein bisschen Geld gespendet.

**Comment by mdzio** [comment]
Das Projekt ruht nicht. Es hat in den letzten 2 Monaten nur wenig von meinem Freizeitkontingent abbekommen. Wahrscheinlich finden sich aber im Weihnachtsurlaub ein paar freie Stunden.
Dieser Eintrag steht auch als nächstes auf der Umsetzungsliste.

**Comment by pburgmer** [comment]
Cool. Danke für die Rückmeldung und deine Arbeit!

**Comment by ManniAT** [comment]
Super, danke für die Info und schöne Feiertage, samt gutem Rutsch.

**Comment by mdzio** [comment]
Adressen für den Zugriff über Web-Sockets:
```
ws://ccu-ip:2121/ws-mqtt
wss://ccu-ip:2122/ws-mqtt
```
Nach 1-2 Tagen Testbetrieb wird die Version 0.11.0 mit Web-Socket-Unterstützung veröffentlicht.
