### ISSUE TITLE
CCU-Jack Iobroker alle werte als Json String ? {"ts":1711175673466,"v":47,"s":0}

### ISSUE THREAD

**Issue by FraatTailscale** [mdzio/ccu-jack#172]
Hallo, ich versuche gerade den CCU-Jack in Iobroker einzubinden. Bekomme aber jeden Wert das in einem Json format (glaube ich) angezeigt. 

{"ts":1711175673466,"v":47,"s":0}

![2024-03-22_14h53_28](https://github.com/mdzio/ccu-jack/assets/100598566/19b60556-2e04-4880-9439-566453ec89b5)

Gibt es eine Möglichkeit nur die Werte gesendet zu bekommen? 
Ich habe über 150 Geräte und möchte nicht 24/7 irgendwelche Scripte laufen lassen um die richtingen Werte zu parsen.

**Comment by mdzio** [comment]
Im CCU-Jack gehört zu jedem Messwert immer der Zeitpunkt des Auslesens aus dem Sensor (ts), der Wert an sich (v) und der Zustand (s). Dieser Aufbau der MQTT-Nachrichten ist so fest im CCU-Jack einprogrammiert.

Es ist nicht unüblich über MQTT Nachrichten mit zusätzlichen Inhalt zu verschicken. In IO-Broker müsste doch dazu auch Funktionalität eingebaut sein. Am besten fragst Du mal im IO-Broker-Forum nach, wie am besten die Werte verarbeitet werden können.

**Comment by mdzio** [comment]
Ich schließe mal diesen Eintrag. Bei Bedarf kann er wieder geöffnet werden.
