### ISSUE TITLE
support of asyncio

### ISSUE THREAD

**Issue by kw123** [mdzio/ccu-jack#180]
would it be possible to have a listener the only gets updates from ccujack if there are any changes instead of constantly pulling all channels?

thanks

Karl

**Comment by mdzio** [comment]
This is already possible via the MQTT interface.

However, polling values also causes little computing load and network bandwidth. I also don't want to implement HTTP long polling or a reverse channel. A WebSocket is functionally identical to MQTT and has no advantages.
