### ISSUE TITLE
CCU-jack als Bridge im IOBroker wie Werte an Jack Gerät

### ISSUE THREAD

**Issue by berlinchris81** [mdzio/ccu-jack#182]
Hallo Team, ich habe ein Mqtt Instanz auf dem IOBroker laufen und auf der RaspberryMatic ein CCU-Jack addon. Im MQTT ist die CCU-Jack instanz zusehen und auch einige devices - Ich habe ein Jackgerät in der CCU (jack...9 weil ich schon ne Weile teste) erzeugt und binde Sie an eine Variable in meinem MQTT - ist da was falsch oder bin ich auf dem Holzweg?
![screen1](https://github.com/mdzio/ccu-jack/assets/8849407/7a6a74b4-c695-441e-92a7-bbf35e1314ca)
![screen2](https://github.com/mdzio/ccu-jack/assets/8849407/6180eeeb-cae6-41c6-90c7-c8919a1faf56)

chris

**Comment by mdzio** [comment]
Den EXTRACTOR bitte mal auf ALL setzen.

Wenn es immmer noch nicht funkioniert, dann über das Web-UI des CCU-Jacks den Log-Level auf TRACE stellen und eventuelle Fehlermeldungen im Log (ebenfalls über das UI mögloch) beim Empfang einer MQTT-Nachricht beobachten.

**Comment by berlinchris81** [comment]
OK also hab log auf trace und ALL gesetzt - kann keine Fehler sehen -  ich hab mal alles angehängt vielleicht seht ihr/du den Fehler

chris

![mqttExplorer](https://github.com/mdzio/ccu-jack/assets/8849407/801e5e92-3055-42df-b1dc-1502286bff55)
![raspimatic](https://github.com/mdzio/ccu-jack/assets/8849407/b4fd88b8-5d34-4950-9d7e-edf57b41f764)
[trace.xlsx](https://github.com/user-attachments/files/15974978/trace.xlsx)

**Comment by mdzio** [comment]
Ich nehme an, dass 192.168.2.100 nicht der MQTT-Server vom CCU-Jack ist. Du musst als erstes die MQTT-Nachrichten zum MQTT-Server des CCU-Jacks weiterleiten. Dies funktioniert mit der [Bridge-Funktionalität](https://github.com/mdzio/ccu-jack/wiki/MQTT-Bridge).

Dann den MQTT-Explorer mit dem MQTT-Server des CCU-Jacks verbinden. Dort sollten dann die Ereignisse zu sehen sein. Dann das zugehörige Topic beim Gerät eintragen.

**Comment by berlinchris81** [comment]
Leider wird das nicht ganz klar. 192.168.2.100:1885 ist der IOBroker MQTT server - dieser Empfängt auch die Daten von CCU-Jack. Wie mach ich jetzt der Raspimatic klar das es zu CCU-Jack weiterleiten soll? Hab mich an der Anleitung auf der github Seite langgehangelt. 
[ccu-jack.txt](https://github.com/user-attachments/files/15975515/ccu-jack.txt)
So schaut die CCU-jack.cfg aus zum großen Teil von der Webseite.

**Comment by berlinchris81** [comment]
Großen Dank für deine Bemühungen.... danke

**Comment by mdzio** [comment]
Im Abschnitt _Incoming_ müsste folgender Eintrag hinzugefügt werden:
```json
      "Incoming": [
        {
          "Pattern": "Infodisplay/verbrauch",
          "LocalPrefix": "IOBroker/",
          "RemotePrefix": "",
          "QoS": 0
        },
        ...
      ]
```

Dann sollte der Wert auch im MQTT-Server des CCU-Jacks auftauchen.

Als _TOPIC_ für den Analogwertempfänger wird dann _IOBroker/Infodisplay/verbrauch_ gesetzt.

**Comment by berlinchris81** [comment]
Muss leider mind. 1  Woche auf Dienstreise, Ich probier es dann aus. 

LG Chris

**Comment by mdzio** [comment]
Funktioniert es jetzt? Ansonsten bitte melden.
