### ISSUE TITLE
CCU-Jack (V2.9.1) shellyplus1pm Integration: Steuerung von der Homematic-CCU3/ RasberryMatic aus funktioniert nicht

### ISSUE THREAD

**Issue by alegrianer** [mdzio/ccu-jack#184]
Hallo zusammen,
ich habe letzte Woche erfolgreich einen shelly1pm via CCU Jack ins RasberryMatic integriert.
Jetzt wollte ich einen weiteren, moderneren shellyplus1pm integrieren.
Die Integration, speziell die Info-Kanäle vom Typ: MQTT Analogwerteempfänger, funktioniert tadellos und Informationen werden zu der CCU korrekt übertragen.
Beim Kanal Typ „MQTT Schaltaktor mit Rückmeldung“ klappt es bei dem shellyplus1pm nicht mit der Steuerung von der CCU aus.
Der Ist-Zustand wird korrekt, via dem Feedback_topic, übertragen.
Commandtopic und Payload Eintrag und On/Off Pattern sind genau der Unterschied zum shelly1pm. Mit den RPC-Einträgen scheint es (bei mir) ein Problem zu geben, obwohl ich die Doku exakt befolge.

Die Einträge:
SWITCH|COMMAND_TOPIC:
shellies/shellyplus1pm-cc7b5c853a94/events/rpc

SWITCH|RETAIN:  aktiviert

SWITCH|ON_PAYLOAD:
{&#34;id&#34;:0, &#34;src&#34;:&#34;shellies/shellyplus1pm-cc7b5c853a94/rpc-response&#34;, &#34;method&#34;:&#34;Switch.Set&#34;, &#34;params&#34;:{&#34;id&#34;:0,&#34;on&#34;:true}}

SWITCH|OFF_PAYLOAD:
{&#34;id&#34;:0, &#34;src&#34;:&#34;shellies/shellyplus1pm-cc7b5c853a94/rpc-response&#34;, &#34;method&#34;:&#34;Switch.Set&#34;, &#34;params&#34;:{&#34;id&#34;:0,&#34;on&#34;:false}}

SWITCH|FEEDBACK_TOPIC: 
shellies/shellyplus1pm-cc7b5c853a94/status/switch:0

SWITCH|ON_PATTERN:
&#34;output&#34;:true

SWITCH|OFF_PATTERN:
&#34;output&#34;:false

SWITCH|MATCHER:
CONTAINS

Dazu der Auszug aus dem MQTT Explorer:
![image](https://github.com/user-attachments/assets/3179e058-433d-4b2d-a049-a55bb2402132)

Die MQTT Config im Shelly:
![image](https://github.com/user-attachments/assets/5ac2fb54-5725-447b-b199-57ec6fe74a4d)

Hat jemand eine Idee, warum sich der Shelly shellyplus1pm  sich nicht von der CCU aus bedienen lässt?
Eine weitere Debug-Idee wäre schon hilfreich

Vielen Dank vorab.

**Comment by mdzio** [comment]
Ich habe endlich Zeit gefunden, dass mal anzuschauen.

Folgende Einstellungen habe ich anders:

SWITCH|COMMAND_TOPIC:
`shellies/shellyplus1pm-[Serien-Nr.]/rpc`

Also ohne `/events`!

**Comment by alegrianer** [comment]
Hallo Mathias, das war's !  Vielen Dank für den Hinweis. Jetzt klappt es !
