### ISSUE TITLE
[FEATUREREQUEST] Lesen aus MQTT-Broker in Systemvariable

### ISSUE THREAD

**Issue by jabba80** [mdzio/ccu-jack#21]
Wenn man in der Logikverarbeitung der CCU einen Wert aus dem MQTT-Broker verwenden möchte, wäre es doch ganz nützlich (ähnlich, wie beim Publish) die Beschreibung der Variablen um das Schlüsselwort MQTT (oder MQTT_SUB) + das gewünschte Topic ergänzen zu können. Das würde dann ein _subscribe_ "auslösen" und dann bei Änderung der Message die Systemvariable updaten.

**Comment by mdzio** [comment]
Generell wird bereits ein _Subscribe_ für jede Systemvariable automatisch durchgeführt. Das Topic lautet sysvar/set/_ISE-ID_. Die ISE-ID ist die ID der Systemvariable in der ReGaHss. Im _Navigator_ des CCU-Jacks werden die _Topics_ zu jeder Systemvariable auch angezeigt. 

Das _Topic_ oder Datenformat kann in diesem Fall natürlich nicht angepasst werden. Das Problem sollte im CCU-Jack aber generell gelöst werden. Beispielsweise in Form einer virtuellen Klemmleiste. Auf diese könnten beliebige Signale (z.B. MQTT-Topics) aufgelegt werden und dann mit beliebigen Datenpunkten verbunden werden. Dazu werde ich ein neues Issue eröffnen.

Generell finde ich die Idee auch gut, das Kommentarfeld der Systemvariablen für eine etwaige MQTT-Konfiguration zu verwenden. Leider ist das bei Gerätedatenpunkten nicht vorhanden.

**Comment by mdzio** [comment]
#53 sollte diesen Anwendungsfall auch abdecken.
