### ISSUE TITLE
MQTT client mode

### ISSUE THREAD

**Issue by ManniAT** [mdzio/ccu-jack#24]
Can ccu-jack run as a MQTT client?
I already run a Mosquitto server and want to integrate my CCU3.

**Comment by manolo4711** [comment]
You can integrate your CCU3 with a mqtt bridge... 
Add to your "main" Mosquitto server 
```
connection external-bridge
address 192.168.x.x:1883 (the CCU3 IP)
topic ... (add some topics what you want to have on your "main" Mosquitto server. 
```

**Comment by mdzio** [comment]
Since a workaround already exists, this improvement will not be addressed for now. However, this entry will be kept open.

**Comment by mdzio** [comment]
Duplicat von #12.
