### ISSUE TITLE
Json object return type

### ISSUE THREAD

**Issue by Plurax** [mdzio/ccu-jack#25]
Hi,

may be I missed it - I would like to use some variable as complex JSON object. That means in contrast to the measurements and status values, I'd like to save a config for my webui within a variable.
This together with MQTT websockets (currently I use twistd+autobahn on localhost for testing) would move on my own LCARS like GUI (attachment). I would use it for the configuration of the GUI on load.

BR
Plurax
![LCARSui](https://user-images.githubusercontent.com/10424872/102895724-81808000-4465-11eb-9f7f-92ab16a780db.png)

**Comment by mdzio** [comment]
The MQTT server can already store arbitrary JSON objects in arbitrary topics. For this, the retain flag of the message must be set. The payload must be structured as follows: `{"v":{ any valid JSON object }}`
However, the messages with retain flag are currently not yet persisted on a data carrier.

Another idea is to use a CCU system variable of type string to store and retrieve a stringified JSON object.

**Comment by Plurax** [comment]
MQTT retain would require to set it up once on startup. Thus I would have the necessity of a startup routine which holds the configuration. I want to keep the ui config (and ideally the broker IP, too) out of the react app.

I would appreciate the "string" variable path. For this I dont need the mqtt access, as the config might be big (currently I fetch it on load initially and create a device tree context with paths similar to the mqtt topics. So the value updates are done on mqtt websocket receive. 
With this I would be able to configure the ui in the CCU3 without other dependencies and keep config code out of the project.

**Comment by mdzio** [comment]
This is already all possible as follows:

When loading the application, the configuration can be read out from a specific system variable via HTTP-GET, e.g. on the address `/sysvar/1234/~pv`. For this purpose, the ID of the system variable must be known. The ID can be determined via an HTTP GET on address `/sysvar` (system variable name must match property `title`).

If the web application is provided by the CCU-Jack itself, the host name does not have to be configured. The web application can be copied into the subdirectory `webui`.

**Comment by Plurax** [comment]
Thanks for clarification (and the web app path tip). For the record: Placing JSON in a string variable can cause code (JS) injection if someone is able to set the variable. Sparetime is rare but it works currently this way...
