### ISSUE TITLE
Gerätetyp (z.B. HmIP-SWDO-I) als Eigenschaft zur Geräteliste hinzufügen

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#28]
In der Geräteliste (/device) soll bei den Verweisen die Eigenschaft type (Gerätetyp) hinzugefügt werden.

Idee aus #26.

**Comment by mdzio** [comment]
Die Umsetzung ist aufwändig, da die [Bibliothek für die REST-API](https://github.com/mdzio/go-veap) erweitert werden müsste. Sie ist daher erste einmal nicht geplant.

**Comment by twendt** [comment]
Kein Problem, ich iteriere nun über alle Devices und lade die Infos. Das hat bei mir wunderbar funktioniert. Meine Umgebung ist allerdings nicht sehr groß. Wenn User Probleme haben sollten, dann kann ich da zur Not ein Caching einbauen.
Die Infos werden nur beim Pairing von Geräten im Homey benötigt, das ist pro Gerät nur eine einmalige Aktion.

**Comment by mdzio** [comment]
Mit der Umsetzung von #77 können nun alle Geräte inkl. Eigenschaften mit einer Anfrage abgefragt werden.
