### ISSUE TITLE
Docker-Image

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#32]
Docker-Image für eine einfache Installation auf unterschiedlichsten Plattformen.

**Comment by ThetaGamma** [comment]
funktionales Dockerfile nun zum Testen freigegeben

**Comment by mdzio** [comment]
Vielen Dank. Das Docker-Image werde ich bei Gelegenheit mal näher anschauen. Ich denke aber, dass noch weitere Ports (2122 und  8883) nach außen geführt werden müssen.

**Comment by ThetaGamma** [comment]
guter Hinweis! Ich hab' die TLS Ports zum Dockerfile und compose hinzugefügt

**Comment by ptweety** [comment]
Ich habe auch mal drauf geschaut und ein paar Anmerkungen hinterlassen: https://github.com/ThetaGamma/ccu-jack/issues/2#issue-805662999

**Comment by ptweety** [comment]
Ich weiß nicht, wo es hinpasst. Damit das Log direkt im Container-Log auftaucht wäre dies meine Empfehlung für die entsprechende Config-Option:

```
  "Logging": {
    "Level": "INFO",
    "FilePath": "/dev/stdout"
  },
```

<img width="948" alt="Bildschirmfoto 2021-02-10 um 18 46 31" src="https://user-images.githubusercontent.com/24972862/107550087-e5573780-6bd0-11eb-9b9e-27825b1c1003.png">

**Comment by ThetaGamma** [comment]
Nach meiner Erfahrung ist das nicht notwendig. Ich hab die Logging Destination nicht explizit im Filepath angegeben und sehe die Logs trotzdem mit "docker logs ..." bzw portainer. Aber es wäre sinnvoll diese Einstellung im Readme zu erwähnen, wenn jemand mit einer bestehenden Config auf Docker migriert

**Comment by mdzio** [comment]
Mit der Version 1.1.0 können nun alle Pfade zu benötigten Dateien und Verzeichnissen konfiguriert werden. Der Pfad zur Konfigurationsdatei kann über den Kommandozeilenparameter `-config` gesetzt werden. Dir übrigen Pfade (Zertifikate, Web-UI-Verzeichnis) können in der Konfigurationsdatei angepasst werden.

**Comment by ThetaGamma** [comment]
passt! läuft nach einem ersten Test bei mir bei alles gut mit gemounteter config und eigenem Cert-Verzeichnis. Ich passe in meinem Fork nochmal alles an und.... wohin muss ich das dann pushen? deinen Docker Fork? einen neuen PR auf master stellen?

**Comment by mdzio** [comment]
Du kannst den Branch `docker` aus mdzio/ccu-jack ziehen. Dort ist Dein letzter Pull-Request. Dann kannst Du die Änderungen in Deinem Repo auf dem Branch `docker` machen und danach für diesen Branch einen Pull-Request erstellen. Zumindest denke ich, dass es so funktionieren sollte. Pull-Requests für `master` verschiebe ich immer auf einen eigenen Branch.

**Comment by mdzio** [comment]
Falls das komplizeirt ist, kannst Du auch einfach auf Deinem master-Branch die Änderungen vornehmen. Die Änderungen ziehe ich mir dann manuell.
