### ISSUE TITLE
Option um das CCU-Zertifikat zu nutzen

### ISSUE THREAD

**Issue by martgras** [mdzio/ccu-jack#35]
Falls auf der CCU schon ein TLS Zertifikat existiert, könnte dieses verwendet werden anstatt ein neues Zertifikat zu erstellen. 
Die CCU verwendet ein kombiniertes PEM Zertifikat das CA und auch den Key enthält : /etc/config/server.pem 

Eine Möglichkeit ist  /etc/config/server.pem in das CCU-Jack Verzeichnis als  svrcert.pem und svrcert.key zu kopieren .  
````
cd <ccujackdir>
cp /etc/config/server.pem svrcert.pem
cp /etc/config/server.pem svrcert.key
````

Oder CCU-Jack überprüft beim start ob  /etc/config/server.pem vorhanden ist und benutzt dann dieses Zertifikat

Begündung:
Ich erstelle meine Zertifikate über meine eigene CA der bereits in allen Browsern vertraut wird und möchte gerne darauf verzichten immer wieder neuen Zerts vertauen zu müssen

**Comment by ThetaGamma** [comment]
Nur um sicher zu gehen: momentan ist die implementierte Logik für das Zertifikat

- prüfe ob Zertifikat im konfigurierten Verzeichnis
- Wenn nein, erzeuge neue CERTs im BinDir von ccu-jack

Für die Umsetzung im Docker wäre es aber viel besser, wenn die Zertifikate im konfigurierten Verzeichnis erzeugt werden anstatt im bindir - dann kann man diese über einen mount (z.B. -v $PWD/cert:/app/cert )persistent machen

**Comment by martgras** [comment]
Hatte ich mir auch schon überlegt. Ich wollte nur möglichst wenig daran ändern wie es bisher funktioniert hat.


Wer auch immer die Zertifikate gerne in bindir haben möchte kann den Pfad dann relativ angeben
