### ISSUE TITLE
Programme der CCU

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#4]
Es sollte die Möglichkeit bestehen, die Programme der CCU aufzulisten und anzustoßen.

**Comment by StefanGubler** [comment]
Das wäre natürlich von Vorteil, wenn CCU-Jack ein "universelles" und komplettes CCU-Interface werden soll.

**Comment by mdzio** [comment]
Etwas Dokumentation ist bei den [CURL-Beispielen](https://github.com/mdzio/ccu-jack/blob/master/doc/curl.md#programme-der-ccu) zu finden.

**Comment by mdzio** [comment]
Die Funktionalität sollte auch über MQTT zur Verfügung stehen.

**Comment by mdzio** [comment]
Implementiert in v0.9.0
