### ISSUE TITLE
Healthcheck Endpunkt und Programm bereitstellen

### ISSUE THREAD

**Issue by ptweety** [mdzio/ccu-jack#41]
Hallo @mdzio,

für das Dockerfile hatte ich einen _healthcheck_ vorgeschlagen. Dort wird schlicht innerhalb des Containers ein Aufruf mit _curl_ auf `http://localhost:2121` ausgeführt und auf die HTTP return codes `200` oder `401` geprüft. Diese Lösung ist nicht besonders schön und bricht natürlich, sobald der Benutzer den Port in der _ccu-jack.cfg_ ändert.

Wäre es möglich einen entsprechenden Status direkt in `./ccu-jack` vorzuhalten, diesen evtl. per Kommandozeile oder HTTP-Endpunkt (ggfs. auch nur intern für `localhost:80/health`) bereitzustellen und dann das ganze per separatem Programm `./healthcheck` an den Benutzer/Container zu melden?

Referenzen:
- Beispiel-App: https://github.com/Soluto/golang-docker-healthcheck-example/blob/master/healthcheck/healthcheck.go
- k8s Konzept: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

**Comment by mdzio** [comment]
Ein HTTP-GET auf `http://localhost:2121/ui` ist von den Benutzerberechtigungen nicht betroffen. Der Port kann zur Not aus der Konfigurationsdatei ermittelt werden. Einen neuen HTTP-Endpunkt für den Healthcheck würde ich daher nicht hinzufügen. Dieser müsste dann auch wieder konfigurierbar sein. 
Sicherlich kann der Healthcheck auch in Go implementiert werden. Aber für einen einfachen HTTP-GET würde ich erst einmal bei `curl` bleiben.

**Comment by ptweety** [comment]
Ok, das funktioniert auch ganz gut, wenn der Healthchekc dann z.B. so konfiguriert ist:

```
# Add a healthcheck (default every 30 secs)
HEALTHCHECK --interval=30s --timeout=5s --start-period=40s --retries=3 \
  CMD curl -Isf -o /dev/null -w "%{scheme}/%{http_version} %{http_code}\n" http://localhost:2121/ui/ || exit 1
```

Ich mache dann hier mal zu.
