### ISSUE TITLE
Installation auf piVCCU auf Raspberry Pi 4 funktioniert nicht

### ISSUE THREAD

**Issue by urbanfi** [mdzio/ccu-jack#47]
Aus der Zuordnung der Distributionen zum Zielsystem geht nicht hervor, welche für die Installation von ccu-jack auf pivCCU3 korrekt ist. 
Bei der Installation von pivCCu3 auf einem Raspberry4 funktioniert die Version für "RaspberryMatic auf Raspberry Pi 4" nicht.
Es muss die Version " CCU3 oder RaspberryMatic auf Raspberry Pi 2, 3" installiert werden.
Eine entsprechende Anmerkung würde dem ein oder anderen sicher einiges an Fehlersuche ersparen.

**Comment by urbanfi** [comment]
Ich habe es eben nochmal probiert.
Die Installation aus der Webui erfolgt ohne Fehlermeldung. CCU-Jack wird als Addon angezeigt und lässt sich unter http://192.168.X.XXX:2121/ui/#!/navigator auch aufrufen.
Allerdings erscheint hier die Fehlermeldung:
![image](https://user-images.githubusercontent.com/83707283/118039185-593fe200-b370-11eb-9429-fc98585b33df.png)

Wenn ich mich per ssh auf der CCU anmelde und in /usr/local/addons/ccu-jack den Befehl ./ccu-jack aufrufe erhalte ich folgende Ausgabe:
![image](https://user-images.githubusercontent.com/83707283/118038528-850e9800-b36f-11eb-86ed-ea737c0997da.png)

file ccu-jack liefert dies (ARM aarch64
![image](https://user-images.githubusercontent.com/83707283/118038608-9f487600-b36f-11eb-9550-8b208d3333a7.png)

CPU-Info allerdings den ARMv7
![image](https://user-images.githubusercontent.com/83707283/118038866-f2222d80-b36f-11eb-9ab7-b195c4f9c442.png)

Hier noch Detail-Info zum Raspberry:
![image](https://user-images.githubusercontent.com/83707283/118039090-39102300-b370-11eb-8ef3-36b3997ceee6.png)

**Comment by mdzio** [comment]
piVCCU verwendet wohl ein 32 Bit-Betriebssystem. Das ist aber auch klar, da piVCCU auf Raspberry Pi OS basiert, welches nur für 32 Bit freigegeben ist. Ich werde entsprechend die Dokumentation der Download-Tabelle anpassen.
