### ISSUE TITLE
Setzen von Werten in SysVars möglich ?

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-jack#5]
Hallo

Wie der Titel schon beschreibt, können damit auch Werte in SysVars gesetzt werden ?

lg Richard

**Comment by mdzio** [comment]
Ja.

**Comment by roe1974** [comment]
wie ist die syntax bei sysvars ?

**Comment by mdzio** [comment]
* Über die Adresse `http://<IP der CCU>:2121/sysvar` wird eine Liste aller Systemvariablen zurückgegeben.
* Dort die gewünschte Systemvariable heraussuchen und die angegebene ID unter `href` notieren.
* Zum Setzen muss dann ein HTTP-PUT auf die Adresse `http://<IP der CCU>:2121/sysvar/<ID>/~pv` ausgeführt werden. Der Body vom PUT-Request ist dann der zu setzende Wert, z.B. `{"v":123}`

Mit dem Kommandozeilenwerkzeug `curl` sieht der Aufruf (unter Linux) wie folgt aus:
`curl -X PUT -d '{"v":123}' http://<IP der CCU>:2121/sysvar/<ID>/~pv`
