### ISSUE TITLE
Virtuelle Geräte für eine bessere Integration in die CCU-Automatisierung

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#52]
Bisher lag das Augenmerk darauf, dass externe Applikationen leicht über die MQTT- oder REST-API auf CCU-Datenpunkte zugreifen können. In der Version 2 des CCU-Jacks wird der Schwerpunkt auf eine leichtere Integration in die CCU-Automatisierung (z.B. in die CCU-Programme) gelegt. 

Dafür soll der CCU-Jack virtuelle Geräte auf der CCU anlegen können. Diese können wie reale HM-Geräte über die Web-UI bedient, konfiguriert, in Programmen abgefragt und von Programmen gesteuert werden. Das Innenleben der Geräte wird je nach Anwendungszweck entworfen.

Die erste Typ von virtuellen Geräten realisiert rein statische Geräte ohne interne Logik. Dies dient dazu neue Datenpunkte zu generieren, die mit CCU-Programmen direkt verknüpft werden können. Dadurch ist der funktional eingeschränkte Umweg über Systemvariablen nicht mehr nötig.

**Fortschritt:**

- [X] Implementierung fehlender XML-RPC-Methoden für Geräteschnittstellenprozesse
- [X] Basisfunktionalität eines Geräteschnittstellenprozesses
- [X] Hülle für ein Gerät
- [X] Hülle für den Wartungskanal
- [X] Hülle für ein Taster-Kanal
- [X] Hülle für ein Schalter-Kanal
- [X] Anpassung des Start-Skripts, damit der CCU-Jack vor der ReGaHss gestartet wird. 

Meilenstein:  Erste auf der CCU funktionierende virtuelle Geräte.

- [X] Laden der bisher erstellten virtuellen Geräte aus der Konfigurationsdatei.
- [x] Erweiterung CCU-Jack Web-UI zur Verwaltung der virtuellen Geräte.
- [X] Anbindung der virtuellen Geräte an die REST-API
- [X] Anbindung der virtuellen Geräte an die MQTT-API

Meilenstein: Veröffentlichung CCU-Jack mit virtuellen Geräten.

Erweiterungen:

- [x] Hülle für einen analogen Messwert (z.B. wie bei HmIP-MIO16-PCB)
- [ ] Hülle für einen analogen Stellwert (z.B. wie bei HmIP-FROLL)

**Comment by frootmig** [comment]
Gibt es irgendeine Möglichkeit bei der Entwicklung dieses Features sinnvoll mitzuhelfen? Ich wüsste nicht wo man anfangen müsste.

**Comment by mdzio** [comment]
Virtuelle Geräte funktionieren bereits testweise bei mir auf der CCU. Ich habe den aktuellen Fortschritt im ersten Kommentar aufgeschlüsselt. Ein paar Punkte müssen aber noch erledigt werden, bevor sie im CCU-Jack veröffentlicht werden.

Für eine eventuelle Mithilfe bei der Entwicklung werden schon sehr gute Kenntnisse in der Programmiersprache Go (Backend) oder Javascript, Mithril und Bootstrap (Frontend) benötigt.

Allerdings freue ich mich auch über Mithilfe beim Testen oder der Erstellung von Tutorials.

**Comment by mdzio** [comment]
Virtuelle Geräte werden ab Version 2 unterstützt, die in den nächsten Tagen erscheinen wird.
Eine[ Dokumentation zu den virtuellen Geräten ist hier](https://github.com/mdzio/ccu-jack#virtuelle-ger%C3%A4te) zu finden.
