### ISSUE TITLE
Dockerfile und build-release.sh passen nicht für einen Raspberry

### ISSUE THREAD

**Issue by kedvsk** [mdzio/ccu-jack#56]
Zwei Probleme: 
- hart codiertes *tar.gz für linux/amd64: ccu-jack-linux-${BUILD_VERSION}.tar.gz
- wget bricht bei der Erstellung des Images ab (tar.gz wurde vorab an einen Raspberry angepasst): 
```
Step 6/11 : RUN wget -q -O - "https://github.com/mdzio/ccu-jack/releases/download/v1.1.1/ccu-jack-ccu3-rm-rp2+3-1.1.1.tar.gz" | tar -xvzC . &&     mkdir -p /app/conf /app/cert /data &&     adduser -h /app -D -H ccu-jack -u 1000 -s /sbin/nologin &&     chown -R ccu-jack:ccu-jack /data && chmod -R g+rwX /data &&     chown -R ccu-jack:ccu-jack /app && chmod -R g+rwX /app
 ---> Running in 627488d713af
wget: bad address 'github.com'
tar: invalid magic
tar: short read
The command '/bin/sh -c wget -q -O - "https://github.com/mdzio/ccu-jack/releases/download/v1.1.1/ccu-jack-ccu3-rm-rp2+3-1.1.1.tar.gz" | tar -xvzC . &&     mkdir -p /app/conf /app/cert /data &&     adduser -h /app -D -H ccu-jack -u 1000 -s /sbin/nologin &&     chown -R ccu-jack:ccu-jack /data && chmod -R g+rwX /data &&     chown -R ccu-jack:ccu-jack /app && chmod -R g+rwX /app' returned a non-zero code: 1
```

**Comment by mdzio** [comment]
@ThetaGamma Kannst Du hier weiterhelfen?

**Comment by ThetaGamma** [comment]
Ich kann's mir mal anschauen. Hab zufällig am letzten WE meine CCU auf dem Raspi in einen Container geschoben. 
Was mich stutzig macht: wieso kann er beim Build github.com nicht auflösen? - sieht mir irgendwie nach Netzwerk Problem aus...

**Comment by kedvsk** [comment]
Auf diesem Raspberry baue ich alle Container. Vom Raspberry selbst ausgehend funktioniert auch der wget Befehl. Das sieht mir eher danach aus, dass auf dem Basisimage noch etwas fehlt. 
Es hängt auch kein Proxy im Netzwerk, der in Verbindung mit Docker Probleme verursachen könnte.

**Comment by ThetaGamma** [comment]
@kedvsk Also ich hab exakt deinen wget in mein Dockerfile auf dem Raspi 2 eingebaut und sonst nix angepasst und es läuft tadellos durch. Anbei mein Dockerfile
[Dockerfile.zip](https://github.com/mdzio/ccu-jack/files/6633868/Dockerfile.zip)
Ich denke, ich werde die Gelegenheit nutzen und das erzeugte Image gleich noch beim docker-hub hochladen.

**Comment by kedvsk** [comment]
FYI:
FROM alpine liefert auch aktuell noch den gleiche Fehlermeldung (war also auch nichts temporäres)
Direkt im Anschluss basierend auf "FROM debian" funktioniert zumindest der wget:

```
...
Step 8/8 : RUN wget -q -O - "https://github.com/mdzio/ccu-jack/releases/download/v1.1.1/ccu-jack-ccu3-rm-rp2+3-1.1.1.tar.gz" | tar -xvzC .
 ---> Running in 142d388bc166
update_script
addon/
addon/README.md
addon/LICENSE.txt
addon/ccu-jack-default.cfg
addon/VERSION
addon/update_hm_addons.tcl
addon/third-party-licenses/
addon/third-party-licenses/gorilla-handlers-license.txt
addon/third-party-licenses/mithril-js-license.txt
addon/third-party-licenses/spectre-css-license.txt
addon/third-party-licenses/surgemq-license.txt
addon/webui/
addon/webui/app.js
addon/webui/components.js
addon/webui/config.js
addon/webui/favicon.png
addon/webui/index.html
addon/webui/navigator.js
addon/webui/utils.js
addon/webui/watcher.js
addon/webui/ext/
addon/webui/ext/mithril.js
addon/webui/ext/spectre-icons.css
addon/webui/ext/spectre.css
rc.d/
rc.d/ccu-jack
etc/
etc/monit-ccu-jack.cfg
www/
www/config.cgi
www/update-check.cgi
addon/ccu-jack
Removing intermediate container 142d388bc166
 ---> 54f0879dc8b8
Successfully built 54f0879dc8b8
Successfully tagged ccu-jack:latest
Successfully tagged ccu-jack:1.1.1
root@SMITH99:/tmp/ccu-jack# 

```
mit Test-Dockerfile:

```
FROM debian

ARG BUILD_DATE
ARG BUILD_VERSION

LABEL org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.version=$BUILD_VERSION \
      org.opencontainers.image.title="CCU-Jack" \
      org.opencontainers.image.description="REST/MQTT-Server for the HomeMatic CCU" \
      org.opencontainers.image.vendor="CCU-Jack OpenSource Project" \
      org.opencontainers.image.authors="mdzio <info@ccu-historian.de>" \
      org.opencontainers.image.licenses="GPL-3.0 License" \
      org.opencontainers.image.url="https://github.com/mdzio/ccu-jack" \
      org.opencontainers.image.documentation="https://github.com/mdzio/ccu-jack/blob/master/README.md"

USER root
RUN apt-get update && apt-get -y install wget

# Set work directory
WORKDIR /

# Get the latest relase from github and extract it locally
RUN wget -q -O - "https://github.com/mdzio/ccu-jack/releases/download/v1.1.1/ccu-jack-ccu3-rm-rp2+3-1.1.1.tar.gz" | tar -xvzC .

```
So, wo liegt das Problem? An meiner Dockerinstallation auf einem RPI3 und der Umgebung eher nicht. Eher am Alpine Basisimage. Warum geht es dann bei Dir?

**Comment by ThetaGamma** [comment]
Gute Frage! Ich habe das Dockerfile nochmal auf einem jungfräulichen Rasbian Image ausprobiert: läuft! Das einzige was mir jetzt noch spontan in den Sinn kommen würde, wäre dieses Rate Limit vom Docker Hub￼ - obwohl ich mir nicht vorstellen kann, dass du als Privatnutzer an dieses Limit heran kommst… ￼ https://www.docker.com/increase-rate-limits

**Comment by kedvsk** [comment]
Das Alpine Image kann ich problemlos per Pull-Request abholen. Das Problem liegt dann m.E. darin, dass der Zugriff auf Github Probleme bereitet. Das Alpine-Image sollte ja ok sein, sonst würde es bei Dir nicht funktionieren.

**Comment by ThetaGamma** [comment]
noch eine (abwegige?) Idee, wenn auch off-topic zu dem issue ;-) 
Falls es alle deine Zugriffe auf Github betrifft: ich habe (vor allem Abends) grottige downloadraten von github (im 1k Bereich) mit VPN bekomme ich meine 100Mbit Leitung ausgelastet (scheinen auch andere zu haben https://telekomhilft.telekom.de/t5/Telefonie-Internet/Amazon-AWS-S3-Github-downloads-sehr-langsam-nicht-nutzbar/td-p/4910937)

**Comment by mdzio** [comment]
Das Problem ist anscheinend benutzerspezifisch. Ich schließe mal den Eintrag. Bei Bedarf kann er wieder eröffnet werden.
