### ISSUE TITLE
MQTT-Bridge Funktionalität

### ISSUE THREAD

**Issue by sbehnsen** [mdzio/ccu-jack#57]
Es wäre schön, wenn man den MQTT Server auch als Bridge konfigurieren könnte. In vielen Systemen gibt es schon einen MQTT Server, and damit könnte man die CCU mit ccu-jack dann direkt an den existierenden MQTT Server hängen.
Ebenfalls könnte man damit dann auch einfach mehrere CCUs bestimmte Daten direkt an einen MQTT Server im Internet schicken lassen. Last but not least, wenn die Bridge Konfiguration auch mehrere Remote MQTT Server unterstützt, dann bekommt man auch noch Failover...

**Comment by mdzio** [comment]
Siehe auch #12. 

In der Regel kann der existierende MQTT-Server bereits als Bridge konfiguriert werden, sodass die Funktionalität im CCU-Jack nicht benötigt wird.

**Comment by bergernetch** [comment]
Wie wäre es, wenn man statt einem internen einfach einen externen MQTT server angeben könnte?

**Comment by mdzio** [comment]
MQTT-Bridge Funktionalität wird in der nächsten Version enthalten sein. 

[Hier ist die Dokumentation dazu zu finden.](https://github.com/mdzio/ccu-jack/wiki/MQTT-Bridge)
