### ISSUE TITLE
CORS Error bei API Zugriff aus Angular App

### ISSUE THREAD

**Issue by tikodu** [mdzio/ccu-jack#6]
Moderne Webanwendungen erwarten den Response-Header `Access-Control-Allow-Origin` in der Antwort von Server. Andernfalls wird die Antwort abgeblockt und nicht weiter verarbeitet.

**Aktueller Workaround**: Proxy zwischen CCU und WebApp, welcher den Header setzt.

Das Setzen des folgenden Headers in jeder Response würde das Problem beheben:
`Access-Control-Allow-Origin: *`

**Comment by mdzio** [comment]
Der eine Header könnte relativ schnell eingebaut werden.
Laut [MDN web docs](https://developer.mozilla.org/de/docs/Web/HTTP/CORS) müssen wohl auch sogenannte _Preflight Requests_ (HTTP-Methode OPTIONS) unterstützt werden, wenn die HTTP-Methode _PUT_ verwendet werden soll.

**Comment by mdzio** [comment]
In der Standardkonfiguration werden nun alle anfragenden Quellen zugelassen (`Access-Control-Allow-Origin: *`). Falls die Authentifizierung eingeschaltet ist (s.a. Kommandozeilenoptionen `-user` und `-password`) muss die Anfragequelle explizit zugelassen werden (s.a. CORS-Spezifikation). Dies erfolgt mit der Kommandozeilenoption `-cors`.
Beispiel: Die Web-Applikation auf dem Host `https://example.com` soll mit Authentifizierung auf die VEAP-API zugreifen können. Dafür muss die Kommandozeilenoption `-cors https://example.com` gesetzt werden.
*Preflight Requests* werden ebenfalls unterstützt.

**Comment by tikodu** [comment]
Ich bekomme via Web-Anwendung leider noch immer die Fehlermeldung `Access to XMLHttpRequest at 'https://***:2122/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`.
Daten lassen sich nur mit einem Workaround abrufen: Authentifizierung abschalten und im Get-Request den Header 'Content-Type' auf 'text/plain' setzen (also nur ein Simple Request laut https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests). Sobald ich den Header 'Content-Type' auf 'application/json' setze oder einen Authentifizierungsheader setze, schlägt der Preflight-Request (OPTIONS) fehl mit Status Code 403. Die CORSOrigins in der ccu-jack.cfg sind entsprechend konfiguriert.
Ich nutze CCU-Jack in der Version 2.0.48
[cors_error_samples.zip](https://github.com/mdzio/ccu-jack/files/7518794/cors_error_samples.zip)

**Comment by mdzio** [comment]
Danke für das Beispiel. Das Ergebnis ist bei das gleiche.

Allerdings sieht es wohl so aus, dass CORS nur für das HTTP(S)-Protokoll und nicht für das File-Protokoll (file://) spezifiziert ist. 

Wenn Du aber Dein Beispiel in den Ordner `webui\custom` im CCU-Jack-Installationsverzeichnis kopierst, `apiUrl = '/'` setzt und dann das Beispiel mit `https://<CCU-Jack-IP>:2122/ui/custom/cors_error_samples.html` aufrufst, dann sind alle 3 Tests erfolgreich. Wahrscheinlich klappt es auch mit jedem beliebigen anderen Web-Server.

**Comment by tikodu** [comment]
Danke für die Anregung, den CCU Jack Web-Server zu verwenden. Ich konnte es damit auch erfolgreich testen. Von einem anderem Web-Server tritt das Problem jedoch weiterhin auf. Habe dieses Beispiel auf meinem NAS laufen: https://ip-nas/cors_error_samples.html --> Fehler wie bereits oben beschrieben.
Das Problem tritt auch aus einer Angular Anwendung auf, welche in einem Docker Container auf Basis des Nginx Images gehostet ist.

**Comment by mdzio** [comment]
Die Header `Content-Type` und `Authorization` lassen wohl CORS fehlschlagen. Ich werde für die beiden Header mal eine Ausnahme einbauen.

**Comment by mdzio** [comment]
Erste Tests sehen gut aus. Der CORS-Zugriff wird ebenfalls für HTML-Dateien aus dem Dateisystem (file://) funktionieren, wenn die CORS-Konfiguration folgendermaßen gesetzt wird:
```
"CORSOrigins": [
      "null"
    ],
```

**Comment by tikodu** [comment]
Vielen Dank! Klappt wunderbar - auch aus einer Angular Anwendung heraus, die auf einem anderen Webserver läuft
