### ISSUE TITLE
Lesen eines Datenpunktes als Textwert

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#63]
Derzeitig wird beim Lesen eines Datenpunktes immer ein JSON-Objekt der Form `{"v":123.456,"ts":1483228800000,"s":0}` zurückgegeben. Die JSON-Rückgabe kann von einigen Clients nur umständlich verarbeitet werden. Der Wert soll als reiner Text ohne Zeitstempel und Status zurückgegeben werden können.

Beispiel-Anfrage: `GET /a/b/c/~pv?format=simple`
Rückgabe: `123.456`

**Comment by pburgmer** [comment]
Eine Alternative könnte es sein dafür den Accept Header zu benutzen statt eines URL Parameters. Siehe https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Accept

**Comment by mdzio** [comment]
Das wäre sogar die bessere Lösung gewesen. Aber viele einfache HTTP-Clients in Geräten können höchstens einen HTTP-GET und auch nur ohne HTTP-Header-Angaben durchführen. Diese Verbesserung ist nur eine Hilfestellung für solche Clients. Wenn immer möglich, sollte die JSON-Antwort auch verwendet werden.

**Comment by mdzio** [comment]
[Weitere Dokumentation](https://github.com/mdzio/ccu-jack#vereinfachter-zugriff)
