### ISSUE TITLE
Aussperren durch Zugriffsberechtigungen verhindern

### ISSUE THREAD

**Issue by tikodu** [mdzio/ccu-jack#67]
Wenn in der UI im Bereich "Zugriffsberechtigungen" alle angelegten Nutzer deaktiviert werden, ist eine Nutzung der UI bzw. der REST/MQTT Endpunkte nicht mehr möglich. Es wird weiterhin nach einem User/Passwort verlangt. Dieser Umstand kann nur durch eine manuelle Anpassung der ccu-jack.cfg + anschließenden Neustart des AddOns wieder rückgängig gemacht werden (Einträge unter Users löschen oder mindestens einen User Active=true setzen).

Meine Erwartungshaltung: Wenn alle User deaktiviert sind ist keine Authentifizierung erforderlich. Für diesen Fall sollte dennoch eine Warnmeldung angezeigt werden, dass Vollzugriff für unangemeldete User besteht, da alle konfigurierten User deaktiviert sind.

**Comment by mdzio** [comment]
Ich denke auch, dass das sinnvoll ist.
