### ISSUE TITLE
CCU Jack unreachable when installed in Home Assistant Add-on - RaspberryMatic CCU

### ISSUE THREAD

**Issue by jutonium** [mdzio/ccu-jack#68]
Hi
I am not sure if the add on is running within a dockerized Raspberrymatic within Home Assistant or if the port(s) cannot be reached. I guess it is the latter since the Log states:
`Starting Third-Party Addons: OK`

The configuration of the add on does not list the CCU-Jack ports. Is there a way to add these?

Thank you

**Comment by mdzio** [comment]
You can find the ports to open [in this image](https://github.com/mdzio/ccu-jack/blob/master/doc/ccu-firewall.png). 

If the process `ccu-jack` is searched for, you can determine whether it is running.

**Comment by mdzio** [comment]
Please create a new issue if there are new findings.
