### ISSUE TITLE
Konfigurierbare Einheit für MQTT-Analogwertempfänger

### ISSUE THREAD

**Issue by mdzio** [mdzio/ccu-jack#74]
Eventuell kann auch die Kanal-Bezeichnung "Eingangsspannung" angepasst werden. (s.a. CUxD Transform Wrapper Device)
Dies sollte dann auch für den _Statischen Analogwerteingang_ umgesetzt werden.

**Comment by etofi** [comment]
Das sollte eigentlich nicht so schwer sein - oder? Ich frage damit die aktuelle Leistung in Watt ab.
Kann man sagen wann das eingebaut wird?

**Comment by mdzio** [comment]
Ich habe mal einen Versuch gestartet: Die vom CCU-Jack angepasste Einheit wird leider von der CCU nicht übernommen. Ich nehme an, dass nach dem Anlegen eines virtuellen Gerätes/Kanals die Eigenschaften einmalig von der CCU gelesen werden und in der ReGaHss gespeichert werden. Sie können dann nachträglich nicht angepasst werden. Die Einheit müsste also beim Anlegen des virtuellen Gerätes bereits mitgegeben werden.

**Comment by etofi** [comment]
Warum braucht man da überhaut eine Einheit? Einfach weglassen. Man kann den Namen des Kanals ja entsprechend anpassen.

**Comment by mdzio** [comment]
Der Aufwand ist zu hoch für dieses kleine Feature. Ich schließe damit diesen Eintrag. Falls sich neue Erkenntnisse ergeben, kann er wieder geöffnet werden.
