### ISSUE TITLE
Ansteuerung von Gruppen

### ISSUE THREAD

**Issue by nerk** [mdzio/ccu-jack#8]
Gruppen scheinen leider nicht unterstützt zu werden. Ich habe hier eine Gruppe aus Wand- und Heizungsthermostat. Dafür wird im Homematic-UI ein virtuelles Gerät angezeigt. In Openhab bzw. im Homematic-UI kann man das virtuelle Gerät direkt ansprechen, ccu-jack kennt allerdings offenbar nur reale Devices.

Ich könnte beide Geräte wahrscheinlich separat mit den gleichen Werten ansteuern, ist aber unschön.

Ansonsten vielen Dank für die Software, funktioniert soweit bestens.

**Comment by mdzio** [comment]
Bitte mal Folgendes testen: In der Datei `/usr/local/etc/config/rc.d/ccu-jack` des installierten Add-Ons die Zeilen 17 bis 22 wie folgt abändern:

```
# CCU interfaces (comma separated without spaces)
if grep -q 'BidCos-Wired' /etc/config/InterfacesList.xml 2>/dev/null; then
  OPT_ITFS=bidcosrf,bidcoswired,hmiprf,virtualdevices
else
  OPT_ITFS=bidcosrf,hmiprf,virtualdevices
fi
```
(jeweils `,virtualdevices` hinzufügen)

Danach den CCU-Jack oder die Zentrale neu starten. Tauchen dann die virtuellen Geräte auf?

**Comment by nerk** [comment]
Funktioniert leider nicht (habe nur im Navigator nachgeschaut). Offenbar wird das virtuelle Device (bei mir  *INT0000001*) gefunden. Erscheinen tut es dann aber nirgends.

Hier der entsprechende Teil aus dem Log:

```
Mar 4 18:16:43 de.eq3.ccu.server.BaseHMServer INFO  [Thread-1] Starting HMServer done                                                                                                                                 
Mar 4 18:16:52 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: xmlrpc_bin://127.0.0.1:3199
Mar 4 18:16:52 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: 1008                                                                     
Mar 4 18:16:52 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-14] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand       
Mar 4 18:16:52 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-14] updateDevicesForClient -> 7 device addresses will be added                                 
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-3] (un)registerCallback on LegacyServiceHandler called from url: http://127.0.0.1:2121/RPC2                            
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-0] init finished                                                                                                       
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-0] Added InterfaceId: CCU-Jack-HmIP-RF                                                                        
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil INFO  [vert.x-worker-thread-0] updateDevicesForClient CCU-Jack-HmIP-RF -> 88 device addresses will be added                                         
Mar 4 18:17:02 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] (un)registerCallback on VirtualDeviceHandlerRega called from url: http://127.0.0.1:2121/RPC2
Mar 4 18:17:02 de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega INFO  [vert.x-eventloop-thread-1] Added InterfaceId: CCU-Jack-VirtualDevices                                           
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-2] (un)registerCallback on LegacyServiceHandler called from url: xmlrpc_bin://127.0.0.1:31999                   
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-1] init finished                                                                                                
Mar 4 18:17:02 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-0] Added InterfaceId: 1009                                                                             
Mar 4 18:17:13 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-14] set ready config of INT0000001                                                      
Mar 4 18:17:13 de.eq3.ccu.virtualdevice.service.internal.rega.BackendWorker INFO  [vert.x-worker-thread-14] Execute BackendCommand: de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand
Mar 4 18:17:13 de.eq3.ccu.virtualdevice.service.internal.rega.BackendUpdateDevicesCommand INFO  [vert.x-worker-thread-14] updateDevicesForClient -> 7 device addresses will be added    
Mar 4 18:21:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: 0 Accesspoints in Queue                                           
Mar 4 18:21:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used           
Mar 4 18:21:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: Eventlistener Handler utilization: 0/50 used                      
Mar 4 18:26:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: 0 Accesspoints in Queue                                           
Mar 4 18:26:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used           
Mar 4 18:26:32 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-4] SYSTEM: Eventlistener Handler utilization: 0/50 used                      
Mar 4 18:26:32 de.eq3.cbcs.lib.remotecommadapter.device.service.AccessPointWatchdog INFO  [vert.x-eventloop-thread-4] SYSTEM: Access Point Watchdog running periodic connection check...
```

**Comment by mdzio** [comment]
Der Log-Auszug lässt noch viele Fragen offen. Ich selbst besitze keine Wand- und Heizungsthermostate. Daher komme ich so nicht weiter. Wahrscheinlich ist aber ein CCU-Backup hilfreich. Kann vielleicht eins zur Verfügung gestellt werden? Eine E-Mail-Adresse ist [hier](https://ccu-historian.de/index.php?n=CCU-Historian.ImpressumAmpHaftungsausschluss) zu finden.

**Comment by nerk** [comment]
Ein Backup möchte ich nicht so gerne versenden. Die CCU-Installation befindet sich auch momentan in Betrieb und ist nicht an meinem Hauptwohnsitz. Wenn die Heizperiode vorbei ist, werde ich mal bei Gelegenheit versuchen, mittels Debugger etwas mehr herauszufinden.

**Comment by mdzio** [comment]
Das kann ich verstehen. Alternativ kann mir auch die nötige Hardware (leihweise) zur Verfügung gestellt werden.

**Comment by nerk** [comment]
Ist es eigentlich möglich, manuell eine Gruppe anzulegen und dieser Gruppe irgendein Gerät hinzuzufügen? Ich habe das noch so nicht ausprobiert. Falls ja könnte man so herausfinden, warum Gruppen nicht angezeigt werden. Ich kann aktuell zwar remote auf meine CCU zugreifen, möchte aber möglichst wenig daran herumspielen, solange ich nicht direkt vor Ort bin.

**Comment by mdzio** [comment]
Soweit ich weiß, ist das Anlegen einer Gruppe nur mit bestimmten Geräten möglich. Aber ich sehe gerade, dass ein Tür-/Fensterkontakt, den ich habe, dafür ausreicht. Dann kann ich nun etwas testen.

**Comment by mdzio** [comment]
Der Fehler lag in der CCU (wie schon so oft). Ich habe im CCU-Jack einen Workaround eingebaut. Bei Gelegenheit die neue Version bitte testen.

**Comment by nerk** [comment]
Danke, werde ich testen, sobald ich wieder vor Ort bin.

**Comment by nerk** [comment]
Funktioniert leider noch nicht. Genau diese Stelle hatte ich ja bereits auch testweise manuell geändert, wenn ich mich nicht irre?

**Comment by mdzio** [comment]
Bitte mal in der Datei `/usr/local/etc/config/rc.d/ccu-jack` die Option `OPT_LOGLEVEL=trace` setzen. Die erstelle Log-Datei vom CCU-Jack ist dann unter `/var/log/ccu-jack.log` zu finden. Seriennummern können geschwärzt werden.

**Comment by StefanGubler** [comment]
Ich habe das getestet mit einer Gruppe aus einem Thermostat HM-CC-RT-DN und einem Fenstersensor. Die Gruppe wird korrekt aufgelistet und ist ansprechbar. SET_TEMPERATURE konnte gesetzt werden. Getestet mit 08.3 auf Windows und 0.8.3 auf virtual-ccu x86.
Bedingung ist, dass ccu-Jack mit Interface VirtualInterfaces gestartet ist.

**Comment by mdzio** [comment]
Danke für das Testen.

@StefanGubler: Die angegebene Version 08.3 wurde bisher nicht veröffentlicht. Meinst Du V0.8.2?

Zur Info: Die Fehlerbehebung für die Gruppen ist nicht im CCU-Jack-Projekt zu finden, sondern in der Bibliothek [github.com/mdzio/go-lib](https://github.com/mdzio/go-lib). Also vor dem Bauen die Bibliothek aktualisieren.

**Comment by nerk** [comment]
Möglicherweise funktioniert es doch. Ich glaube, ich habe einen blöden Fehler beim Testen gemacht.  Kann ich leider zur Zeit nicht verifizieren, da Off-Site.

Vielleicht kann das Issue geschlossen werden? Falls es bei meinem nächsten Test nicht klappt, melde ich mich nochmal.
