### ISSUE TITLE
Fehler: 	(1/mosquitto.ccujack) Error retrieving subscribers list: memtopics/nextTopicLevel: Cannot publish to $ topics

### ISSUE THREAD

**Issue by andbez** [mdzio/ccu-jack#82]
Hallo.

Ich nutze RaperryMatic mit aktiviertem CuxD-Protokoll. Für Home-Assistant nutze ich einen eigenen Moqsuitto-Server, der auf den CCU-Jack-Mosquitto-Server zugreift. Dazu habe ich auch eine Nutzer in CCU-Jack angelegt. Grundsätzlich funktioniert es, leider werden aber die Daten nicht mehr im eigenen Mosq-MQTT-Server aktualisiert und es gibt o.g. Fehlermeldung. Im Speziellen geht es hier um eine Wetterstation KS300.

Fehler (alle unter dem Thema mqtt):
(1/mosquitto.ccujack) Connection unexpectedly closed, sending Will message
(1/mosquitto.ccujack) Un-/Retaining of message failed: memtopics/nextTopicLevel: Cannot publish to $ topics
(1/mosquitto.ccujack) Error retrieving subscribers list: memtopics/nextTopicLevel: Cannot publish to $ topics
Decoding of connect message failed: Connection Refused, unacceptable protocol version

Setting für MQTT-Bridge im eigenen Mosq-Server:
connection ccujack
address raspmatic.ip:1883
topic device/status/CUX3101234 read 0
remote_username USERNAME
remote_password PASSWORD
start_type automatic

Jemand eine Idee, das Problem anzugehen/zu lösen?

**Comment by mdzio** [comment]
Bitte mal folgende Konfigurationsoption mit in die `mosquitto.conf` aufnehmen:
bridge_protocol_version mqttv311

**Comment by andbez** [comment]
Hi.

Vielen Dank für den Hinweis. Ich habe dies der Conf hinzugefügt und alles neu gestartet. Leider keine Veränderung. mqttv311 ist wohl auch der Default-Wert bei Mosquitto.

**Comment by mdzio** [comment]
Im Eintrag #57 wurde berichtet, dass es wohl grundsätzlich funktioniert. Vielleicht findest Du dort noch einen Tipp.

**Comment by andbez** [comment]
Hallo.

Vielen Dank für den Hinweis. Bin jetzt auf die neue Version mit Bridge gegangen und das funktioniert.
