### ISSUE TITLE
Direkte Verknüpfung virtueller Geräte

### ISSUE THREAD

**Issue by sbormann** [mdzio/ccu-jack#87]
Hallo, erst mal großes Lob und Danke an die Entwickler!!
Eine Frage: Ist es möglich, virtuelle Geräte in Direkt-Verknüpfungen einzufügen?
Ich habe einen Display-Taster und würde den gerne zur Steuerung von MQTT-Geräten (mit Feedback) nehmen. Da wäre es prima, wenn das per Direktverknüpfung ginge, da ich dann im Displaytaster das Feedback angezeigt bekäme.
Vielen Dank!

**Comment by mdzio** [comment]
Das ist technisch nicht möglich. Direktverknüpfungen sind nur innerhalb einer Gerätefamilie (z.B. HM, HM-Wired, HM-IP) möglich.

**Comment by sbormann** [comment]
Ah, ok, schade. Ich dachte halt, weil man die virtuellen Kanäle der CCU ja auch direkt verknüpfen kann. Danke!
