### ISSUE TITLE
SET_POINT_MODE  bei Heizung

### ISSUE THREAD

**Issue by sikousikou** [mdzio/ccu-jack#88]
SET_POINT_MODE  bei Heizungsgeräte sowie Heizungsgruppen lässt sich nicht ändern über MQTT (device/set/INT0000004/1/SET_POINT_MODE) oder CCU Jack Webinterface

**Comment by sikousikou** [comment]
Titel | xxxx_xxxx:1 - SET_POINT_MODE
Beschreibung |  
control | HEATING_CONTROL_HMIP.SETPOINT_MODE
default | 0
flags | 1
id | SET_POINT_MODE
maximum | 3
minimum | 0
mqttSetTopic | device/set/xxxxxx/1/SET_POINT_MODE
mqttStatusTopic | device/status/xxxxxxx/1/SET_POINT_MODE
operations | 7
special | ()
tabOrder | 0
type | INTEGER
unit
<br class="Apple-interchange-newline">

**Comment by ptweety** [comment]
Ich erinnere mich da an Diskussionen, dass der `SET_POINT_MODE` nur zur Anzeige, der `CONTROL_MODE` aber zur Änderung da sei. Oder eben umgekehrt ... erinnern ist hart ...

**Comment by mdzio** [comment]
Da dies geklärt ist, schließe ich mal den Eintrag.
