### ISSUE TITLE
ccu-jack.cfg im Wiki fehlerhaft dokumentiert

### ISSUE THREAD

**Issue by joergr** [mdzio/ccu-jack#94]
Auf der Wiki Seite https://github.com/mdzio/ccu-jack/wiki/AddOn-Installationsdetails wird als Pfad bzw. Dateiname

`/usr/local/addons/ccu-jack/ccu-jack.config`

angegeben. Statt Endung `.config` sollte es heißen `.cfg`

**Comment by mdzio** [comment]
Vielen Dank für den Hinweis. Ich habe es entsprechend angepasst.
