### ISSUE TITLE
CCU2 +CuxD -> MQTT -> Home Assistant

### ISSUE THREAD

**Issue by Wox1** [mdzio/ccu-jack#97]
Hallo,

zuerst mal danke und großem Respekt für Dein Projekt hier!
Ich bin leider ein kompletter Anfänger im Bereich Mqtt. Ich wollte "nur" die CCU2 mit den CuxD Geräten in Home Assistent einbinden und musste schnell merken, dass das nicht  funktioniert. Nun habe ich gelesen, dass es hier das Mqtt Protokoll gibt. Also habe ich einen mqtt Broker auf Home Assistent installiert, und dieses Addon für die CCU2 gefunden (1.1.1). Nun komme ich nicht mehr weiter. Wie kann ich nun die beiden Systeme dazu bringen miteinander zu kommunizieren? Kann mir hier jemand helfen? Ich vermute in der Konfig Datei aber wie kann ich da einen mqtt broker einrichten?

**Comment by mdzio** [comment]
Der CCU-Jack V1 für die CCU2 kann nicht mit externen MQTT-Brokern/Severn verbunden werden. (Der CCU-Jack V2 für die CCU3 kann dies.) 

Der CCU-Jack ist aber selber auch MQTT-Server. In Home Assistant müsste also ein MQTT-Client instaliert und konfiguriert werden. Bei der Konfiguration von Home Assistant kann ich leider nicht weiter helfen.
