### ISSUE TITLE
MQTT Analogwertempfänger Erweiterungen

### ISSUE THREAD

**Issue by dega2** [mdzio/ccu-jack#99]
Ein super Addon für die Homematic! Ich hätte da ein paar kleine Vorschläge für Verbesserungen:

Aktuell wird der MQTT Analogwertempfänger bei Gerätename bzw. den Kanälen immer "Analog Eingang" angezeigt.
![image](https://user-images.githubusercontent.com/27890269/188497688-a3d29dec-9ea4-444e-9ed2-d34058bccf45.png)
Die macht es bei den Programmen extrem unübersichtlich, wenn man mehrer Eingangswerte hat wie z.B. Helligkeit, Helligkeit in Lux, Temperatur, Batterie, usw.
Außerdem wird der Wert immer als Eingangsspannung dargestellt.
![image](https://user-images.githubusercontent.com/27890269/188498504-0fead14d-f1c3-4783-8f04-d67b0d7c3f24.png)
Es wäre sehr hilfreich wenn man beides über das WebUI pro Kanal benennen könnte und im Idealfall sogar eine Einheit für den Wert wie z.B. C oder Lux angeben könnte.

**Comment by mdzio** [comment]
Für eine größtmögliche Kompatibilität mit der Logik-Schicht (ReGaHss) der CCU, bilden die virtuellen Kanäle des Jacks immer nur Kanäle von real existierenden Geräten nach, hier z.B. vom HmIP-MIO16-PCB.
Sicherlich gibt es Möglichkeiten fiktive Kanäle zu erzeugen, wie dies z.B. der CUxD macht. Das ist aber mit viel Probiererei verbunden, die ich mir nicht zumuten will.
